#### Import all Required Libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

#### Numpy Code

##### List to Array

In [3]:
myList = [1,2,3,4]

arr_1 = np.array( myList )

print( 'L: ', myList, ' Type: ', type(myList) )
print ( 'A1: ', arr_1, ' Type: ', type(arr_1), ' Dimension: ', arr_1.shape )

L:  [1, 2, 3, 4]  Type:  <class 'list'>
A1:  [1 2 3 4]  Type:  <class 'numpy.ndarray'>  Dimension:  (4,)


##### Multi-Dim Array

In [4]:

matrix_1 = [ [1,2,3], [4,5,6], [7,8,9] ]

arr_2 = np.array( matrix_1 )

print( 'M: ', matrix_1, ' Type: ', type(matrix_1) )
print ( 'A2: \n', arr_2, '\n Type: ', type(arr_2), ' Dimension: ', arr_2.shape  )

M:  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]  Type:  <class 'list'>
A2: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
 Type:  <class 'numpy.ndarray'>  Dimension:  (3, 3)


#### Generate Data with Numpy

##### Specific Values

In [5]:

arr_3 = np.arange( 0,11 )
print ( 'A3: ', arr_3, ' Type: ', type(arr_3), ' Dimension: ', arr_3.shape  )

arr_4_even = np.arange( 0,11,2 )
print ( 'A4 Even: ', arr_4_even, ' Type: ', type(arr_4_even), ' Dimension: ', arr_4_even.shape  )

arr_4_odd = np.arange( 1,11,2 )
print ( 'A4 Odd: ', arr_4_odd, ' Type: ', type(arr_4_odd), ' Dimension: ', arr_4_odd.shape  )

arr_5_hundreds = np.arange( 100, 1000, 100 )
print ( 'A5 Hundreds: ', arr_5_hundreds, ' Type: ', type(arr_5_hundreds), ' Dimension: ', arr_5_hundreds.shape  )

A3:  [ 0  1  2  3  4  5  6  7  8  9 10]  Type:  <class 'numpy.ndarray'>  Dimension:  (11,)
A4 Even:  [ 0  2  4  6  8 10]  Type:  <class 'numpy.ndarray'>  Dimension:  (6,)
A4 Odd:  [1 3 5 7 9]  Type:  <class 'numpy.ndarray'>  Dimension:  (5,)
A5 Hundreds:  [100 200 300 400 500 600 700 800 900]  Type:  <class 'numpy.ndarray'>  Dimension:  (9,)


##### Numpy Array of Zeros

In [6]:
arr_6_zeros = np.zeros( 5 )
print ( 'A6 Zeros: ', arr_6_zeros, ' Type: ', type(arr_6_zeros), ' Dimension: ', arr_6_zeros.shape  )

arr_6_zeros_matrix = np.zeros( (2,3) ) 
print ( 'A6 Zero Matrix: \n', arr_6_zeros_matrix, '\n Type: ', type(arr_6_zeros_matrix), ' Dimension: ', arr_6_zeros_matrix.shape  )

A6 Zeros:  [0. 0. 0. 0. 0.]  Type:  <class 'numpy.ndarray'>  Dimension:  (5,)
A6 Zero Matrix: 
 [[0. 0. 0.]
 [0. 0. 0.]] 
 Type:  <class 'numpy.ndarray'>  Dimension:  (2, 3)


##### Numpy Array of Ones

In [7]:
arr_7_ones = np.ones( 7 )
print ( 'A7 Ones: ', arr_7_ones, ' Type: ', type(arr_7_ones), ' Dimension: ', arr_7_ones.shape  )

arr_7_ones_matrix = np.ones( (3,4) ) 
print ( 'A7 Ones Matrix: \n', arr_7_ones_matrix, '\n Type: ', type(arr_7_ones_matrix), ' Dimension: ', arr_7_ones_matrix.shape  )

A7 Ones:  [1. 1. 1. 1. 1. 1. 1.]  Type:  <class 'numpy.ndarray'>  Dimension:  (7,)
A7 Ones Matrix: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 
 Type:  <class 'numpy.ndarray'>  Dimension:  (3, 4)


##### Numpy Array of Random Numbers

In [8]:
# A Uniformly distributed 1-D Array of Numbers
arr_8_random = np.random.rand( 5 )
print ( 'A8 Random:', arr_8_random, 'Type: ', type(arr_8_random), ' Dimension: ', arr_8_random.shape  )

arr_8_rand_matrix = np.random.rand( 4,4 )
print ( 'A8 Random Matrix: \n', arr_8_rand_matrix, '\n Type: ', type(arr_8_rand_matrix), ' Dimension: ', arr_8_rand_matrix.shape  )

single_random_num = np.random.randint( 1,100 )
print ( 'Num:', single_random_num, '\t Type: ', type(single_random_num) )

arr_8_rand_range = np.random.randint( 1,100,12 )
print ( 'A8 12 Random Nums: ', arr_8_rand_range, ' Type: ', type(arr_8_rand_range), ' Dimension: ', arr_8_rand_range.shape  )

A8 Random: [0.29452141 0.16898443 0.40808302 0.9066665  0.60686843] Type:  <class 'numpy.ndarray'>  Dimension:  (5,)
A8 Random Matrix: 
 [[0.66629482 0.90171642 0.71948127 0.19769632]
 [0.76000646 0.10557094 0.74896196 0.69418778]
 [0.69463122 0.96989879 0.3063745  0.45097678]
 [0.93637105 0.90598624 0.7493628  0.65029284]] 
 Type:  <class 'numpy.ndarray'>  Dimension:  (4, 4)
Num: 65 	 Type:  <class 'int'>
A8 12 Random Nums:  [96 36 21 87 48 58 38  2 80 30 20 92]  Type:  <class 'numpy.ndarray'>  Dimension:  (12,)


##### Array ReShape

In [9]:
arr_9_rand_range_matrix = np.random.randint( 100,200,16 )
print ( 'A9 16 Random Nums: ', arr_9_rand_range_matrix, ' Type: ', type(arr_9_rand_range_matrix), ' Dimension: ', arr_9_rand_range_matrix.shape  )

arr_9_reshaped = arr_9_rand_range_matrix.reshape( 4,4 )
print ( 'A9 Reshaped: \n ', arr_9_reshaped, '\n Type: ', type(arr_9_reshaped), ' Dimension: ', arr_9_reshaped.shape  )

A9 16 Random Nums:  [172 129 130 110 145 157 132 150 162 131 184 166 113 125 160 166]  Type:  <class 'numpy.ndarray'>  Dimension:  (16,)
A9 Reshaped: 
  [[172 129 130 110]
 [145 157 132 150]
 [162 131 184 166]
 [113 125 160 166]] 
 Type:  <class 'numpy.ndarray'>  Dimension:  (4, 4)


##### NP Array Methods

In [10]:
arr_10_rand_range = np.random.randint( 200,300,12 )
print ( 'A10 12 Random Nums: ', arr_10_rand_range, ' Type: ', type(arr_10_rand_range), ' Dimension: ', arr_10_rand_range.shape  )

print( 'A10 12 Random Sorted: ', np.sort(arr_10_rand_range), '\t Min Value: ', arr_10_rand_range.min(), ' \t Max Value: ', arr_10_rand_range.max() )
print( 'Mean: ', np.round( arr_10_rand_range.mean(), 2 ), ' \t Sum: ', arr_10_rand_range.sum() )

A10 12 Random Nums:  [296 229 205 264 267 203 253 235 280 227 254 217]  Type:  <class 'numpy.ndarray'>  Dimension:  (12,)
A10 12 Random Sorted:  [203 205 217 227 229 235 253 254 264 267 280 296] 	 Min Value:  203  	 Max Value:  296
Mean:  244.17  	 Sum:  2930


##### NP Array Slicing

In [11]:
print( 'Original Array : ', np.random.randint( 200,300,12 ) )
print( 'First 5 Elements Starting from 1st element: ', arr_10_rand_range[ 1:5 ] )
print( 'All Elements till 8 : ', arr_10_rand_range[ :8 ] )

Original Array :  [283 206 259 285 241 297 231 266 283 255 239 271]
First 5 Elements Starting from 1st element:  [229 205 264 267]
All Elements till 8 :  [296 229 205 264 267 203 253 235]


##### Broadcast Certain Value to the Array

In [12]:
arr_11 = np.random.randint( 200,300,12 )

print( 'Original Array : ', arr_11 )

# Broadcast 100 Value to Even Number Elements

arr_11[ ::2 ] = 100

print( 'Broadcasted Array : ', arr_11 )

Original Array :  [282 224 217 296 250 223 206 240 227 213 218 224]
Broadcasted Array :  [100 224 100 296 100 223 100 240 100 213 100 224]


##### Indexing 2-D Arrays

In [13]:
arrMatrix = np.array( [ [5,10,15], [20,25,30], [35,40,45] ] )
print ( 'A12: \n ', arrMatrix, '\n Type: ', type(arrMatrix), ' Dimension: ', arrMatrix.shape )

print( 'First Row: ', arrMatrix[0] )
# Indices start from 0
print( 'Value at 1,3: ', arrMatrix[0][2] )
print( 'Value at 2,2: ', arrMatrix[1,1] )

# 2-D Array Slicing
print( 'Everything until Row 2 and Column 1 onwards : \n', arrMatrix[ : 2,1 : ] )

A12: 
  [[ 5 10 15]
 [20 25 30]
 [35 40 45]] 
 Type:  <class 'numpy.ndarray'>  Dimension:  (3, 3)
First Row:  [ 5 10 15]
Value at 1,3:  15
Value at 2,2:  25
Everything until Row 2 and Column 1 onwards : 
 [[10 15]
 [25 30]]


##### Generate Arrays based on Condition

In [14]:
arr_12 = np.random.randint( 50,70,12 )

print ( 'A13: ', arr_12 )
bool_arr = (arr_12 % 2 == 0)
print ( 'Bool: ', bool_arr )
print( 'Values from Original Array Satisfying the condition : ', arr_12[ bool_arr ] )

A13:  [61 69 68 51 64 55 56 56 68 53 52 52]
Bool:  [False False  True False  True False  True  True  True False  True  True]
Values from Original Array Satisfying the condition :  [68 64 56 56 68 52 52]


###### Do all the Steps in one Line 

In [15]:
arr_13 = np.random.randint( 20,90,15 )
print( 'Original Array :', arr_13 )
print( 'Conditional Array : ', arr_13 [ arr_13 % 2 == 0 ] )

Original Array : [42 53 67 78 40 69 23 59 49 79 64 72 27 82 27]
Conditional Array :  [42 78 40 64 72 82]


##### Numpy Array Arithmetic

In [16]:
arr_14 = np.random.randint( 10,50,10 )
arr_15 = np.random.randint( 70,100,10 )

print( 'Array #1 : ', arr_14 )
print( 'Array #2 : ', arr_15 )

print( 'Array Add : ', arr_14 + arr_15 )
print( 'Array Sub : ', arr_14 - arr_15 )
print( 'Array Mul : ', arr_14 * arr_15 )
print( 'Array Div : ', np.round (arr_14 / arr_15, 2) )

print( 'Array Scalar Addition : ', arr_14 + 100 )

Array #1 :  [33 37 46 13 38 38 41 36 17 39]
Array #2 :  [99 98 90 98 76 92 72 83 96 87]
Array Add :  [132 135 136 111 114 130 113 119 113 126]
Array Sub :  [-66 -61 -44 -85 -38 -54 -31 -47 -79 -48]
Array Mul :  [3267 3626 4140 1274 2888 3496 2952 2988 1632 3393]
Array Div :  [0.33 0.38 0.51 0.13 0.5  0.41 0.57 0.43 0.18 0.45]
Array Scalar Addition :  [133 137 146 113 138 138 141 136 117 139]


##### Universal Array Functions - Mathematical Operations to be Broadcasted to the entire Array

In [17]:
arr_16 = np.random.randint( 70,100,10 )
print( 'Arr Original : \t \t', arr_16 )
print( 'Square Root of each element : ', np.round (np.sqrt(arr_16), 2) )
print( 'SIN of each element : ', np.round (np.sin(arr_16), 2) )
print( 'Log of each element : ', np.round (np.log(arr_16), 2) )

Arr Original : 	 	 [80 70 93 97 92 84 98 70 80 99]
Square Root of each element :  [8.94 8.37 9.64 9.85 9.59 9.17 9.9  8.37 8.94 9.95]
SIN of each element :  [-0.99  0.77 -0.95  0.38 -0.78  0.73 -0.57  0.77 -0.99 -1.  ]
Log of each element :  [4.38 4.25 4.53 4.57 4.52 4.43 4.58 4.25 4.38 4.6 ]


#### Pandas Code

In [18]:
labels = [ 'a', 'b', 'c' ]
myData = [ 10, 20, 30 ]
arr_18 = np.array( myData )
myDict = { 'a': 10, 'b': 20, 'c': 30 }

In [19]:
series_1 = pd.Series( data= myData )
print( 'Data : \n', series_1, ' Dimension : ', series_1.shape )

Data : 
 0    10
1    20
2    30
dtype: int64  Dimension :  (3,)


In [20]:
# Pandas Series is a Key-Value Type DataStructure, so we can specify the Keys if we want
series_2 = pd.Series( data= myData, index= labels )
print( 'Data : \n', series_2, ' Dimension : ', series_2.shape )

Data : 
 a    10
b    20
c    30
dtype: int64  Dimension :  (3,)


In [21]:
# Instead of a List we can also specify a numpy array
series_3 = pd.Series( arr_18,labels )
print( 'Data : \n', series_3, ' Dimension : ', series_3.shape )

Data : 
 a    10
b    20
c    30
dtype: int32  Dimension :  (3,)


In [22]:
# We can also pass a Dictionary directly which replaces the data and indexes
series_4 = pd.Series( myDict )
print( 'Data : \n', series_4, ' Dimension : ', series_4.shape )

Data : 
 a    10
b    20
c    30
dtype: int64  Dimension :  (3,)


##### Series Index 

In [23]:
series_5 = pd.Series( [1,2,3,4], ['Apple', 'Banana', 'Car', 'Dog'] )
series_6 = pd.Series( [6,7,8,9], ['Apple', 'Banana', 'Bike', 'Dog'] )

print( series_5, '\n', series_6 )
print( 'Vals for Apple :', series_5['Apple'], '\t', series_6['Apple'] )
print( 'Vals for First Element :', series_5[1], '\t', series_6[1] )

Apple     1
Banana    2
Car       3
Dog       4
dtype: int64 
 Apple     6
Banana    7
Bike      8
Dog       9
dtype: int64
Vals for Apple : 1 	 6
Vals for First Element : 2 	 7


###### Series Arithmatic - Same Values (Apple, Banana, Dog) will be calculated and unequal ones (Bike & Car ) Null

In [24]:
 print( 'Add : \n', series_5 + series_6 )
print( 'Sub : \n', series_5 - series_6 )

Add : 
 Apple      7.0
Banana     9.0
Bike       NaN
Car        NaN
Dog       13.0
dtype: float64
Sub : 
 Apple    -5.0
Banana   -5.0
Bike      NaN
Car       NaN
Dog      -5.0
dtype: float64


##### DataFrames - Basically Bunch of Series sharing an index

###### Create DataFrame as pd.DataFrame( Values, Row-Indices, Column-Indices )

In [25]:
from numpy.random import randn 

df_1 = pd.DataFrame( randn(5,4), ['A','B','C','D','E'], ['W','X','Y','Z'] )
df_1

W         X         Y         Z
A -1.502171 -1.418531 -0.966006 -0.542700
B  0.386827  0.448747  0.175532 -0.773469
C -1.529710 -1.602679  0.983551  0.661652
D -0.668999  0.501712 -0.990988 -0.292770
E -0.842790  0.604163 -1.237439  1.204377

In [26]:
print( 'W Column: \n' )
df_1['W']

W Column: 



A   -1.502171
B    0.386827
C   -1.529710
D   -0.668999
E   -0.842790
Name: W, dtype: float64

In [27]:
print( 'W and Z Columns: \n' )
df_1[ ['W', 'Z'] ]

W and Z Columns: 



W         Z
A -1.502171 -0.542700
B  0.386827 -0.773469
C -1.529710  0.661652
D -0.668999 -0.292770
E -0.842790  1.204377

##### Add a New Column by simply stating the Name

In [28]:
df_1[ 'newCol' ] = df_1['W'] + df_1['Z'] 
df_1

W         X         Y         Z    newCol
A -1.502171 -1.418531 -0.966006 -0.542700 -2.044871
B  0.386827  0.448747  0.175532 -0.773469 -0.386641
C -1.529710 -1.602679  0.983551  0.661652 -0.868059
D -0.668999  0.501712 -0.990988 -0.292770 -0.961770
E -0.842790  0.604163 -1.237439  1.204377  0.361586

#### Column = 1 and Row = 0

##### Drop a Column Temporarily

In [29]:
df_1.drop( 'newCol', axis=1 )

W         X         Y         Z
A -1.502171 -1.418531 -0.966006 -0.542700
B  0.386827  0.448747  0.175532 -0.773469
C -1.529710 -1.602679  0.983551  0.661652
D -0.668999  0.501712 -0.990988 -0.292770
E -0.842790  0.604163 -1.237439  1.204377

##### To Drop the Column permanently use inplace=True

In [30]:
df_1.drop( 'newCol', axis=1, inplace=True )
df_1

W         X         Y         Z
A -1.502171 -1.418531 -0.966006 -0.542700
B  0.386827  0.448747  0.175532 -0.773469
C -1.529710 -1.602679  0.983551  0.661652
D -0.668999  0.501712 -0.990988 -0.292770
E -0.842790  0.604163 -1.237439  1.204377

##### To Drop the Row Use Axis = 0 

In [31]:
df_1.drop( 'A', axis=0 )

W         X         Y         Z
B  0.386827  0.448747  0.175532 -0.773469
C -1.529710 -1.602679  0.983551  0.661652
D -0.668999  0.501712 -0.990988 -0.292770
E -0.842790  0.604163 -1.237439  1.204377

###### Same like above permanently with inplace

In [32]:
df_1.drop( 'A', axis=0, inplace=True )
df_1

W         X         Y         Z
B  0.386827  0.448747  0.175532 -0.773469
C -1.529710 -1.602679  0.983551  0.661652
D -0.668999  0.501712 -0.990988 -0.292770
E -0.842790  0.604163 -1.237439  1.204377

##### Selecting Rows - df.loc( Row, Col )

In [33]:
print( 'Selected Row: ' )
df_1.loc[ 'B' ]

Selected Row: 


W    0.386827
X    0.448747
Y    0.175532
Z   -0.773469
Name: B, dtype: float64

In [34]:
print( 'Selected Row-Column Value: ' )
df_1.loc[ 'B','Y' ]

Selected Row-Column Value: 


0.17553162490623306

In [35]:
print( 'Selected Row-Column Combination' )
df_1.loc[ ['B','D'], ['Y','Z'] ]

Selected Row-Column Combination


Y         Z
B  0.175532 -0.773469
D -0.990988 -0.292770

##### Conditional Selection

In [36]:
# Print only positive Values 
boolDataFrame = df_1 > 0
df_1[ boolDataFrame ]

W         X         Y         Z
B  0.386827  0.448747  0.175532       NaN
C       NaN       NaN  0.983551  0.661652
D       NaN  0.501712       NaN       NaN
E       NaN  0.604163       NaN  1.204377

In [37]:
# Print only positive Values 
df_1[ df_1 > 0 ]

W         X         Y         Z
B  0.386827  0.448747  0.175532       NaN
C       NaN       NaN  0.983551  0.661652
D       NaN  0.501712       NaN       NaN
E       NaN  0.604163       NaN  1.204377

In [38]:
# Find Particlar Columns With the specified condition 
df_1['W'][ (df_1['W']) > 0 ]

B    0.386827
Name: W, dtype: float64

###### Multiple Conditions , Logical Operators &, | 

In [39]:
df_1[['W','Y']] [ (df_1['W']>0) & (df_1['Y']>1) ]

Empty DataFrame
Columns: [W, Y]
Index: []

In [40]:
df_1[['W','Y']] [ (df_1['W']>0) | (df_1['Y']>1) ]

W         Y
B  0.386827  0.175532

In [41]:
df_1

W         X         Y         Z
B  0.386827  0.448747  0.175532 -0.773469
C -1.529710 -1.602679  0.983551  0.661652
D -0.668999  0.501712 -0.990988 -0.292770
E -0.842790  0.604163 -1.237439  1.204377

In [42]:
df_1[ 'newColVals' ] = [ 'ABC', 'XYZ', 'PQR', 'LMN' ]
df_1

W         X         Y         Z newColVals
B  0.386827  0.448747  0.175532 -0.773469        ABC
C -1.529710 -1.602679  0.983551  0.661652        XYZ
D -0.668999  0.501712 -0.990988 -0.292770        PQR
E -0.842790  0.604163 -1.237439  1.204377        LMN

##### Find out Missing Values

In [43]:
myDict2 = { 'A': [1,2,np.nan], 'B': [5,np.nan,np.nan], 'C': [9,8,np.nan] }
df_2 = pd.DataFrame( myDict2 )
df_2

A    B    C
0  1.0  5.0  9.0
1  2.0  NaN  8.0
2  NaN  NaN  NaN

###### Drop NaN values

In [46]:
# Drop Any row containing NaN
df_2.dropna()

A    B    C
0  1.0  5.0  9.0

In [47]:
myDict2 = { 'A': [1,2,np.nan], 'B': [5,np.nan,np.nan], 'C': [9,8,np.nan] }
df_2 = pd.DataFrame( myDict2 )
df_2

A    B    C
0  1.0  5.0  9.0
1  2.0  NaN  8.0
2  NaN  NaN  NaN

In [48]:
# Drop a Particular Column with NaN
df_2.dropna( axis=1 )

Empty DataFrame
Columns: []
Index: [0, 1, 2]

In [68]:
myDict2 = { 'A': [1,2,np.nan], 'B': [5,np.nan,np.nan], 'C': [9,8,np.nan] }
df_2 = pd.DataFrame( myDict2 )
df_2

A    B    C
0  1.0  5.0  9.0
1  2.0  NaN  8.0
2  NaN  NaN  NaN

In [51]:
# A Threshhold Value to require you to not get NaN dropped - Min Threshhold to Drop Values
df_2.dropna( thresh=2 )

A    B    C
0  1.0  5.0  9.0
1  2.0  NaN  8.0

##### Fill Values with Mean, or Median whatever makes Sense

In [75]:
myDict2 = { 'A': [1,2,np.nan], 'B': [5,np.nan,np.nan], 'C': [9,8,np.nan] }
df_2 = pd.DataFrame( myDict2 )
df_2

A    B    C
0  1.0  5.0  9.0
1  2.0  NaN  8.0
2  NaN  NaN  NaN

In [72]:
df_2.loc[ 0 ].mean()

5.0

In [73]:
df_2.mean()

A    1.5
B    5.0
C    8.5
dtype: float64

In [67]:
# Fill with a dummy Value
df_2.fillna( value='FV', inplace=True )
df_2

A    B    C
0  1.0  5.0  9.0
1  2.0   FV  8.0
2   FV   FV   FV

In [70]:
# Fill with the Mean of first Row
df_2.fillna( value=df_2.loc[ 0 ].mean(), inplace=True )
df_2

A    B    C
0  1.0  5.0  9.0
1  2.0  5.0  8.0
2  5.0  5.0  5.0

In [76]:
# Fill with the Mean of first Row
df_2.fillna( value=df_2['C'].mean(), inplace=True )
df_2

A    B    C
0  1.0  5.0  9.0
1  2.0  8.5  8.0
2  8.5  8.5  8.5

##### GROUP-BY to Group Rows together based of a column and use Aggregate functions like SUM, MIN, MAX, MEAN etc. to Group using certain property

In [77]:
myData3 = {
    'Company': [ 'GOOG','MSFT','APPL','FB', 'GOOG','MSFT','APPL','FB' ],
    'EmpName': [ 'John', 'Jane', 'Mary', 'Scott', 'James', 'Joey', 'Janice','Sam' ],
    'TotalSales' : [ 100, 200, 300, 500, 600, 700, 800, 900 ]
}

df_3 = pd.DataFrame( myData3 )
df_3

Company EmpName  TotalSales
0    GOOG    John         100
1    MSFT    Jane         200
2    APPL    Mary         300
3      FB   Scott         500
4    GOOG   James         600
5    MSFT    Joey         700
6    APPL  Janice         800
7      FB     Sam         900

In [79]:
# Group By a Column Value - Company
grpByCompany = df_3.groupby( 'Company' )

print( 'Mean by Company : \n' )
grpByCompany.mean()

Mean by Company : 



C:\Users\RD-Coding\AppData\Local\Temp\ipykernel_10504\127952469.py:5: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  grpByCompany.mean()


TotalSales
Company            
APPL          550.0
FB            700.0
GOOG          350.0
MSFT          450.0

###### To get all Statistical Values just use Describe

In [80]:
grpByCompany.describe()

TotalSales                                                      
             count   mean         std    min    25%    50%    75%    max
Company                                                                 
APPL           2.0  550.0  353.553391  300.0  425.0  550.0  675.0  800.0
FB             2.0  700.0  282.842712  500.0  600.0  700.0  800.0  900.0
GOOG           2.0  350.0  353.553391  100.0  225.0  350.0  475.0  600.0
MSFT           2.0  450.0  353.553391  200.0  325.0  450.0  575.0  700.0

In [81]:
# We could flip it with Transpose
grpByCompany.describe().transpose()

Company                 APPL          FB        GOOG        MSFT
TotalSales count    2.000000    2.000000    2.000000    2.000000
           mean   550.000000  700.000000  350.000000  450.000000
           std    353.553391  282.842712  353.553391  353.553391
           min    300.000000  500.000000  100.000000  200.000000
           25%    425.000000  600.000000  225.000000  325.000000
           50%    550.000000  700.000000  350.000000  450.000000
           75%    675.000000  800.000000  475.000000  575.000000
           max    800.000000  900.000000  600.000000  700.000000

##### Merging, Joining and Concatenating

In [90]:
# Create a DataFrame with three columns and an index of 0 to 3
myDict3 = { 'col_1': [100,200,300,100], 'col_2': [888,777,666,888], 'col_3': ['abc','xyz','lmn','pqr'] } 

df_4 = pd.DataFrame( myDict3 )

df_4

col_1  col_2 col_3
0    100    888   abc
1    200    777   xyz
2    300    666   lmn
3    100    888   pqr

###### Finding Unique Values

In [91]:
uniqueCol1 = df_4['col_1'].unique()

print( 'Unique in Column1 : ', uniqueCol1, ' Number of Unique Elements: ', len( uniqueCol1 ) )
print( 'Number of Unique Values, from Pandas :', df_4['col_1'].nunique() )

Unique in Column1 :  [100 200 300]  Number of Unique Elements:  3
Number of Unique Values, from Pandas : 3


In [92]:
uniqueCol2 = df_4['col_2'].unique()

print( 'Unique in Column2 : ', uniqueCol2, ' Number of Unique Elements: ', len( uniqueCol2 ) )
print( 'Number of Unique Values, from Pandas :', df_4['col_2'].nunique() )

Unique in Column2 :  [888 777 666]  Number of Unique Elements:  3
Number of Unique Values, from Pandas : 3


###### Get Count of Each element

In [93]:
df_4['col_1'].value_counts()

100    2
200    1
300    1
Name: col_1, dtype: int64

In [94]:
df_4['col_2'].value_counts()

888    2
777    1
666    1
Name: col_2, dtype: int64

In [95]:
df_4['col_3'].value_counts()

abc    1
xyz    1
lmn    1
pqr    1
Name: col_3, dtype: int64