### Numpy :
- **Numpy** - Numerical Python used for Data Processing
- is written in C and C++ so operations are significantly faster than using Python

### Install and Import Numpy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
# python list
nums = [1,2,3,4,5]
print( 'Python List : ', nums, ' \t Type : ', type(nums) )

# numpy array
npArr_1 = np.array( nums ) 
print( 'Numpy Array : ', npArr_1, ' \t Type : ', type(npArr_1) )

Python List :  [1, 2, 3, 4, 5]  	 Type :  <class 'list'>
Numpy Array :  [1 2 3 4 5]  	 Type :  <class 'numpy.ndarray'>


### Vectorization 

In [4]:
print( 'List requires loop : ', [ n + 10 for n in nums ] )
print( 'NumpyArray vectorized loop #1: ', npArr_1 + 10 )
print( 'NumpyArray vectorized loop #2: ', npArr_1 * 10 )

List requires loop :  [11, 12, 13, 14, 15]
NumpyArray vectorized loop #1:  [11 12 13 14 15]
NumpyArray vectorized loop #2:  [10 20 30 40 50]


***

### Array Creation Numpy and Python
- Python List can have multiple data types
- But Numpy Array can only have one data type which helps with calculations

In [5]:
# List
pyList = [ 1,2,3, 4.5, True, 'Hello' ]
print( 'Val : ', pyList, ' Type : ', type(pyList) )

# Numpy Array
np_Arr_int = np.array( [1,2,3,4,5] )
print( 'Val : ', np_Arr_int, ' Type : ', type(np_Arr_int), ' DataType: ', np_Arr_int.dtype )

np_Arr_float = np.array( [1.5,2.5,3.1,4.7,5] )
print( 'Val : ', np_Arr_float, ' Type : ', type(np_Arr_float), ' DataType: ', np_Arr_float.dtype )

# Specify DataType while creating 
np_Arr_float = np.array( [1.5,2.5,3.5], dtype=np.float32 )
print( 'Val : ', np_Arr_float, 'Float32 DataType instead of Default Float64 : ', np_Arr_float.dtype )

print( "\n Memory consumed per element: \n \t np.int16/np.float16 - 2 Bytes, \n \t np.int32/np.float32 - 4 Bytes, \n \t np.int64/np.float64 - 8 Bytes" )

Val :  [1, 2, 3, 4.5, True, 'Hello']  Type :  <class 'list'>
Val :  [1 2 3 4 5]  Type :  <class 'numpy.ndarray'>  DataType:  int64
Val :  [1.5 2.5 3.1 4.7 5. ]  Type :  <class 'numpy.ndarray'>  DataType:  float64
Val :  [1.5 2.5 3.5] Float32 DataType instead of Default Float64 :  float32

 Memory consumed per element: 
 	 np.int16/np.float16 - 2 Bytes, 
 	 np.int32/np.float32 - 4 Bytes, 
 	 np.int64/np.float64 - 8 Bytes


In [6]:
# Using np.arange() similar to range function - start, stop, step
np_Arr_int = np.arange( 0, 10, 1 )
print( 'arange() : ', np_Arr_int, ' Type : ', type(np_Arr_int) )

arange() :  [0 1 2 3 4 5 6 7 8 9]  Type :  <class 'numpy.ndarray'>


In [7]:
# Arrays of Zeros
npArr_2 = np.zeros( 10 )
print( 'zeros(10) : ', npArr_2, ' Type : ', type(npArr_2) )
# Arrays of Ones
npArr_2 = np.ones( 5 )
print( 'ones(5) : ', npArr_2, ' Type : ', type(npArr_2) )

zeros(10) :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]  Type :  <class 'numpy.ndarray'>
ones(5) :  [1. 1. 1. 1. 1.]  Type :  <class 'numpy.ndarray'>


In [8]:
np_Arr_float = np.random.rand( 5 ) 
print( '5 random floating point values between 0 and 1: ', np_Arr_float )

np_Arr_int = np.random.randint( 10,20, size=5 )
print( '5 random integer values between 10 and 20: ', np_Arr_int )

5 random floating point values between 0 and 1:  [1.37248258e-01 7.16416413e-01 2.43177998e-01 2.55389581e-01
 5.24676905e-04]
5 random integer values between 10 and 20:  [17 12 11 19 11]


### Identity Matrix 
- 1 Values are Diagonal

In [9]:
id_1 = np.eye(3)
print( '3x3 Identity Matrix : \n', id_1 )

id_2 = np.eye(2)
print( '\n 2x2 Identity Matrix : \n', id_2 )

3x3 Identity Matrix : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 2x2 Identity Matrix : 
 [[1. 0.]
 [0. 1.]]


***

### Multi-Dimensional Arrays
- **Dimensions** - Number of Nested Arrays inside of a Numpy Array
- **Shape** - Values will be based on the number of dimensions, 1 value for 1D, 2 values for 2D and 3 values for 3D and so on

In [10]:
np_1D_Arr = np.array( [ 1,2,3,4,5 ] )
print( '1-Dimensional Array :', np_1D_Arr )
print( 'Shape : ', np_1D_Arr.shape, '\t Dimensions : ', np_1D_Arr.ndim, '\t Size: ', np_1D_Arr.size )

np_2D_Arr = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
print( '\n 2-Dimensional Array :\n ', np_2D_Arr )
print( 'Shape : ', np_2D_Arr.shape, '\t Dimensions : ', np_2D_Arr.ndim, '\t Size: ', np_2D_Arr.size )

1-Dimensional Array : [1 2 3 4 5]
Shape :  (5,) 	 Dimensions :  1 	 Size:  5

 2-Dimensional Array :
  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape :  (3, 3) 	 Dimensions :  2 	 Size:  9


***

### Indexing and Slicing
- **Slicing** = [start, stop, step]
- **Indexing** = Particular Element

#### 1-D Array Indexing

In [11]:
np_1D_Arr = np.array( [ 10,20,30,40,50 ] )
print( 'Original Array : ', np_1D_Arr, '\t Shape : ', np_1D_Arr.shape )
print( 'First Element : ', np_1D_Arr[0] )
print( 'Last Element : ', np_1D_Arr[-1] )
print( 'First 3 Elements : ', np_1D_Arr[:3] )
print( 'Elements 1 to 3: ', np_1D_Arr[1:4] )

Original Array :  [10 20 30 40 50] 	 Shape :  (5,)
First Element :  10
Last Element :  50
First 3 Elements :  [10 20 30]
Elements 1 to 3:  [20 30 40]


#### 2-D Array Indexing

In [12]:
# 2-D Array Indexing
np_2D_Arr = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
print( 'Original Array : \n ', np_2D_Arr, '\t Shape : ', np_2D_Arr.shape )
print( 'Element at Row 2, Column 3 = ', np_2D_Arr[1,2] ) # Row,Col
print( 'Element at Row 3, Column 2 = ', np_2D_Arr[2,2] ) # Row,Col
print( 'All Columns in First Row : ', np_2D_Arr[0,:] )
print( 'All Rows in Second Column : ', np_2D_Arr[:,1] )

Original Array : 
  [[1 2 3]
 [4 5 6]
 [7 8 9]] 	 Shape :  (3, 3)
Element at Row 2, Column 3 =  6
Element at Row 3, Column 2 =  9
All Columns in First Row :  [1 2 3]
All Rows in Second Column :  [2 5 8]


#### NP Array Boolean Indexing

In [13]:
np_Arr = np.array( [ 10,22,30,42,55,60,77,84,99 ] )
print( 'Original Array : ', np_Arr, '\t Shape : ', np_Arr.shape )
print( 'Elements Greater than 50 : ',  np_Arr[ np_Arr > 50 ] )
print( 'Even Numbers : ', np_Arr[ np_Arr % 2 == 0 ] )
print( 'Odd Numbers : ', np_Arr[ np_Arr % 2 == 1 ] )

Original Array :  [10 22 30 42 55 60 77 84 99] 	 Shape :  (9,)
Elements Greater than 50 :  [55 60 77 84 99]
Even Numbers :  [10 22 30 42 60 84]
Odd Numbers :  [55 77 99]


### NumPy for Vectorized Operations without using any kind of loop

In [14]:
arr_1 = np.array( [1,2,3,4,5] )
print( 'Array #1 : ', arr_1 )

arr_2 = np.array( [6,7,8,9,10] )
print( 'Array #2 : ', arr_2 )

Array #1 :  [1 2 3 4 5]
Array #2 :  [ 6  7  8  9 10]


#### Element-wise Operations - Perform operations Element by Element 

In [15]:
print( 'Addition = ', arr_1 + arr_2 )
print( 'Subtraction = ', arr_1 - arr_2 )
print( 'Multiplication = ', arr_1 * arr_2 )
print( 'Division = ', arr_1 / arr_2 )

Addition =  [ 7  9 11 13 15]
Subtraction =  [-5 -5 -5 -5 -5]
Multiplication =  [ 6 14 24 36 50]
Division =  [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


#### Scalar Operations:
- **Broadcasting** - Same Value operations to every individual element inside the Numpy Array

In [16]:
print( 'Array #1 : ', arr_1 )
print( 'Power/Exponential (Square) = ', arr_1 ** 2 )
print( 'Power/Exponential (Cube) = ', arr_1 ** 3 )

Array #1 :  [1 2 3 4 5]
Power/Exponential (Square) =  [ 1  4  9 16 25]
Power/Exponential (Cube) =  [  1   8  27  64 125]


***

#### Concatenation - Adding multiple matrices

In [17]:
arr_1 = np.array([1, 2, 3])
print('\nArray #1:\n', arr_1)
print('Shape :', arr_1.shape, '\tDimensions :', arr_1.ndim, '\tSize :', arr_1.size)

arr_2 = np.array([4, 5, 6])
print('\nArray #2:\n', arr_2)
print('Shape :', arr_2.shape, '\tDimensions :', arr_2.ndim, '\tSize :', arr_2.size)

# Vertical stacking: creates a 2D array with arrays as rows
print('\nVertical Concatenation (vStack):\n', np.vstack((arr_1, arr_2)))

# Horizontal stacking: joins the arrays into one longer 1D array
print('\nHorizontal Concatenation (hStack):\n', np.hstack((arr_1, arr_2)))


Array #1:
 [1 2 3]
Shape : (3,) 	Dimensions : 1 	Size : 3

Array #2:
 [4 5 6]
Shape : (3,) 	Dimensions : 1 	Size : 3

Vertical Concatenation (vStack):
 [[1 2 3]
 [4 5 6]]

Horizontal Concatenation (hStack):
 [1 2 3 4 5 6]


***

### Numpy Array Methods:

In [18]:
nums = np.array([20, 49, 33, 23, 54, 53, 23, 18, 27, 38]) 

print( 'Numbers Initially : ', nums )

print( '\t Sorted using Numpy - returns a sorted copy ', np.sort( nums ) )
print( '\t Original Array unchanged ', nums )
print( '\t Numbers Reversed : ', nums[::-1] )
ascending_order = np.sort(nums)
print( '\t Numbers Sort Ascending : ', ascending_order )
descending_order = ascending_order[::-1]
print( '\t Numbers Sort Descending : ', descending_order )

Numbers Initially :  [20 49 33 23 54 53 23 18 27 38]
	 Sorted using Numpy - returns a sorted copy  [18 20 23 23 27 33 38 49 53 54]
	 Original Array unchanged  [20 49 33 23 54 53 23 18 27 38]
	 Numbers Reversed :  [38 27 18 23 53 54 23 33 49 20]
	 Numbers Sort Ascending :  [18 20 23 23 27 33 38 49 53 54]
	 Numbers Sort Descending :  [54 53 49 38 33 27 23 23 20 18]


In [19]:
nums = np.array([20, 49, 49, 23, 53, 53, 20, 18, 20, 38, 23, 18] )

print( 'Numbers with duplicates : ', nums )
unique_nums = np.unique(nums)
print( 'Unique Values : ', unique_nums )

print( 'Search where value is greater than 20 (Positions): ', np.where( unique_nums > 20 ) )
print( 'Search where value is greater than 20 (Actual values): ', unique_nums[np.where( unique_nums > 20 )] )

Numbers with duplicates :  [20 49 49 23 53 53 20 18 20 38 23 18]
Unique Values :  [18 20 23 38 49 53]
Search where value is greater than 20 (Positions):  (array([2, 3, 4, 5]),)
Search where value is greater than 20 (Actual values):  [23 38 49 53]


***

### Dot Product

In [20]:
vector_1 = np.array( [1,2,3] )
vector_2 = np.array( [4,5,6] )
print( '\n Vector #1 : ', vector_1, ' Vector #2 : ', vector_2 )
print( f" Dot Product of Vectors {vector_1} and {vector_2}  = { np.dot(vector_1,vector_2) }")

# Calculation:
# (1×4) + (2×5) + (3×6)
# = 4 + 10 + 18
# = 32

mat_1 = np.array([ [1,2], [3,4] ])
print( '\n Matrix #1 :\n ', mat_1 )
print( 'Shape : ', mat_1.shape, '\t Dimensions : ', mat_1.ndim, '\t Size: ', mat_1.size )

mat_2 = np.array([ [5,6], [7,8] ])
print( '\n Matrix #2 :\n ', mat_2 )
print( 'Shape : ', mat_2.shape, '\t Dimensions : ', mat_2.ndim, '\t Size: ', mat_2.size )

print( '\n Element-wise Multiplication: (mat_1 * mat_2) = \n', (mat_1 * mat_2) )

# NOT matrix multiplication, just position-by-position multiplication.
# [[1*5   2*6]
#  [3*7   4*8]]
# =
# [[5   12]
#  [21  32]]

# Dot Product (Matrix Multiplication) - row × column multiplication:

print( 'Matrix Properties:' )
print( f" Dot Product of Matrices \n {mat_1} \n and \n {mat_2} \n = \n { np.dot(mat_1,mat_2) }")

# First row of Matrix 1 × columns of Matrix 2:
# (1×5 + 2×7) = 5 + 14 = 19  
# (1×6 + 2×8) = 6 + 16 = 22

# Second row of Matrix 1 × columns of Matrix 2:
# (3×5 + 4×7) = 15 + 28 = 43  
# (3×6 + 4×8) = 18 + 32 = 50

# Result:
# [[19 22]
#  [43 50]]


 Vector #1 :  [1 2 3]  Vector #2 :  [4 5 6]
 Dot Product of Vectors [1 2 3] and [4 5 6]  = 32

 Matrix #1 :
  [[1 2]
 [3 4]]
Shape :  (2, 2) 	 Dimensions :  2 	 Size:  4

 Matrix #2 :
  [[5 6]
 [7 8]]
Shape :  (2, 2) 	 Dimensions :  2 	 Size:  4

 Element-wise Multiplication: (mat_1 * mat_2) = 
 [[ 5 12]
 [21 32]]
Matrix Properties:
 Dot Product of Matrices 
 [[1 2]
 [3 4]] 
 and 
 [[5 6]
 [7 8]] 
 = 
 [[19 22]
 [43 50]]


***