In [61]:
import numpy as np

# 1. Create a 3x3x3 array with random values 

In [62]:
arr1 = np.random.random( (3,3,3) )
arr1

array([[[0.3179596 , 0.58087675, 0.16740102],
        [0.08574162, 0.65576483, 0.83837048],
        [0.12569102, 0.61180286, 0.44079821]],

       [[0.79875431, 0.59139648, 0.27734997],
        [0.94163179, 0.91858883, 0.40020562],
        [0.31076716, 0.08240278, 0.31739216]],

       [[0.31621484, 0.53757169, 0.78529669],
        [0.94035473, 0.54265634, 0.17885005],
        [0.50241841, 0.91404873, 0.80571149]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [63]:
arr2 = np.diag(1+np.arange(4), k = -1)

arr2

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [64]:
arr3 = np.zeros ((8,8))

arr3[1::2, ::2]= 1

arr3[::2, 1::2] = 1

arr3

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

# 4. Normalize a 5x5 random matrix

In [65]:
arr5 = np.random.random((5,5))

arr5max, arr5min = arr5.max(), arr5.min()

arr5= (arr5-arr5min)/(arr5max-arr5min)

arr5

array([[0.53346954, 0.61866525, 0.38765068, 0.40276751, 0.43205936],
       [0.48234601, 0.21232357, 0.41003982, 0.38135407, 0.94328387],
       [0.6559046 , 0.29471768, 0.40250583, 0.42129877, 0.30470339],
       [0.        , 0.12981175, 0.30894276, 0.91213034, 0.07963337],
       [0.55017472, 0.50564219, 1.        , 0.81551721, 0.25236004]])

# 5.  How to find common values between two arrays?

In [66]:
arr1 = np.array( [1,7,3,9,4,17] )

arr2 = np.array( [1,7,14,87,34,17] )

arrIntersection = np.intersect1d( arr1, arr2 )

print( 'Array #1 : ', arr1 )
print( 'Array #2 : ', arr2 )
print( 'Array Intersection : ', arrIntersection )

Array #1 :  [ 1  7  3  9  4 17]
Array #2 :  [ 1  7 14 87 34 17]
Array Intersection :  [ 1  7 17]


# 6.How to get the dates of yesterday, today and tomorrow?

In [67]:
today     = np.datetime64('today', 'D')

yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')

tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print( 'Todays Date : ', today )
print( 'Yesterdays Date : ', yesterday )
print( 'Tomorrows Date : ', tomorrow )

Todays Date :  2020-07-26
Yesterdays Date :  2020-07-25
Tomorrows Date :  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [68]:
arr1 = np.random.random( (3,3,3) )

arr2 = np.random.random( (3,3,3) )

print( arr1 )
print( '\n ----\n' )
print( arr2 )
print( '\n ----\n' )
print( arr2 == arr1 )

[[[0.34060091 0.80355245 0.54756551]
  [0.12653267 0.37219346 0.6704988 ]
  [0.1874453  0.63397201 0.71679805]]

 [[0.07856832 0.69711763 0.25837276]
  [0.0346596  0.27531964 0.48353221]
  [0.98077354 0.35906423 0.17050736]]

 [[0.18905294 0.82138544 0.71137282]
  [0.27335455 0.81459149 0.66616627]
  [0.20109481 0.87339143 0.8898254 ]]]

 ----

[[[0.58538464 0.30439647 0.8871732 ]
  [0.34950344 0.63405747 0.43153037]
  [0.67142496 0.0184079  0.66615109]]

 [[0.98583153 0.53489083 0.8172225 ]
  [0.66838772 0.5234696  0.1305576 ]
  [0.83421331 0.30134551 0.16605503]]

 [[0.58830945 0.4068557  0.07946079]
  [0.20869608 0.17288343 0.8410735 ]
  [0.76174915 0.01338239 0.07716847]]]

 ----

[[[False False False]
  [False False False]
  [False False False]]

 [[False False False]
  [False False False]
  [False False False]]

 [[False False False]
  [False False False]
  [False False False]]]


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [69]:
arr7 = np.random.random( 10 )

print( 'Array Before : ', arr7 )

print( 'Max Value : ', arr7[ arr7.argmax() ] )

arr7[ arr7.argmax() ] = 0

print(  'Array After : ', arr7 )

Array Before :  [0.99755213 0.77277714 0.11362146 0.54297035 0.96788392 0.63864475
 0.12275798 0.774219   0.81045967 0.23462959]
Max Value :  0.997552131144241
Array After :  [0.         0.77277714 0.11362146 0.54297035 0.96788392 0.63864475
 0.12275798 0.774219   0.81045967 0.23462959]


# 9. How to print all the values of an array?

In [70]:
arr1 = np.random.random( (3,3,3) )
print( 'Using Print Function : \n' , arr1 )

Using Print Function : 
 [[[0.70373104 0.14358853 0.93502696]
  [0.55015422 0.48536115 0.70228291]
  [0.93562283 0.8330909  0.25205575]]

 [[0.90070331 0.10222877 0.00166626]
  [0.03017403 0.925878   0.29286848]
  [0.62866836 0.14812876 0.24932633]]

 [[0.36242215 0.3859674  0.22250402]
  [0.06739341 0.50573824 0.39092906]
  [0.24795267 0.96320277 0.94914011]]]


# 10.Subtract the mean of each row of a matrix

In [71]:
print("Original matrix:\n")
arr1 = np.random.rand(5,5)
print(arr1)

print("\n Matrix after Subtraction :\n")

arrSub = arr1 - arr1.mean(axis=1, keepdims=True)

print(arrSub)

Original matrix:

[[0.12006048 0.71480812 0.23168953 0.95192827 0.43063112]
 [0.54126071 0.60157631 0.2186642  0.64186899 0.92435218]
 [0.24027896 0.58809596 0.7596283  0.80977507 0.28192028]
 [0.72795749 0.75049576 0.09635427 0.9327317  0.26639363]
 [0.66043257 0.59866675 0.68105302 0.30682925 0.6445522 ]]

 Matrix after Subtraction :

[[-0.36976302  0.22498461 -0.25813398  0.46210476 -0.05919238]
 [-0.04428377  0.01603183 -0.36688027  0.05632451  0.3388077 ]
 [-0.29566076  0.05215625  0.22368859  0.27383536 -0.25401943]
 [ 0.17317092  0.19570919 -0.4584323   0.37794513 -0.28839294]
 [ 0.08212582  0.02035999  0.10274626 -0.27147751  0.06624544]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [72]:
arr1 = np.ones(10)

print( ' Original Array : ', arr1 )

pos = np.random.randint(0,len(arr1),20)

np.add.at( arr1, pos, 1 )

print( ' Modified Array : ', arr1 )

 Original Array :  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 Modified Array :  [3. 3. 1. 6. 2. 2. 2. 2. 6. 3.]


# 12.How to get the diagonal of a dot product?

In [73]:
mat1 = np.random.uniform(0,1,(5,5))

mat2 = np.random.uniform(0,1,(5,5))

print( 'Array 1 : \n', mat1 )
print( 'Array 2 : \n', mat2 )
print( 'Dot Product : \n', np.dot(mat1, mat2) )

diagArr =  np.diag( np.dot(mat1, mat2) )
print( 'Dot Product Diagonal : \n', diagArr )


Array 1 : 
 [[0.99907749 0.48612756 0.90324106 0.82801217 0.07523656]
 [0.71980211 0.70912777 0.80885259 0.74129392 0.9394245 ]
 [0.86643584 0.61076881 0.93058299 0.75165972 0.70139239]
 [0.34400793 0.10419394 0.19544204 0.16390312 0.79923507]
 [0.06884648 0.14930614 0.26547046 0.62054049 0.73676578]]
Array 2 : 
 [[0.50743089 0.14452667 0.29382455 0.51808151 0.04178685]
 [0.08257873 0.52127047 0.07088144 0.9753526  0.70335735]
 [0.19503892 0.35080455 0.25737351 0.69577329 0.34311176]
 [0.34384337 0.18890073 0.95044276 0.83440366 0.39109554]
 [0.59868558 0.66414817 0.67015439 0.15834136 0.09491788]]
Dot Product : 
 [[1.05302327 0.92103869 1.39787951 2.32300979 1.02455548]
 [1.39887534 1.52137517 1.80405364 2.39463191 1.18546025]
 [1.34995944 1.37786912 1.72183042 2.43032116 1.14563376]
 [0.75613077 0.73436542 0.85015641 0.67914665 0.29468252]
 [0.7535012  0.78744948 1.18267192 1.00044322 0.51160135]]
Dot Product Diagonal : 
 [1.05302327 1.52137517 1.72183042 0.67914665 0.51160135]


# 13.How to find the most frequent value in an array?

In [74]:
arr5 = np.random.randint(0,2,17)

print( ' Numpy Array : ', arr5 )

print( 'Most Frequest Value : ', np.bincount(arr5).argmax() )


 Numpy Array :  [0 1 0 1 0 1 1 1 0 0 0 1 0 0 1 0 0]
Most Frequest Value :  0


# 14.How to get the n largest values of an array

In [75]:
arr6 = np.arange(17)

np.random.shuffle(arr6)

n = 5

print( 'Original Array : ', arr6 )

print ( '\n Top ', n, ' largest value : ', arr6[np.argsort(arr6)[-n:]] )

Original Array :  [14 16 11  3  5 15  2  1  0  4  6 10 13 12  7  9  8]

 Top  5  largest value :  [12 13 14 15 16]


# 15.How to create a record array from a regular array?

In [76]:
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')

print( 'Array #1 : ', a1 )
print( 'Array #2 : ', a2 )
print( 'Array #3 : ', a3 )

print( 'Record Array : \n', result )

Array #1 :  [1 2 3 4]
Array #2 :  ['Red' 'Green' 'White' 'Orange']
Array #3 :  [12.2 15.  20.  40. ]
Record Array : 
 [(1, 'Red', 12.2) (2, 'Green', 15. ) (3, 'White', 20. )
 (4, 'Orange', 40. )]
