### Install the numpy package

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


### Import Required Libraries

In [2]:
import numpy as np

# For doing the Array generation Time Calculation
import time

### Numpy :
- **Numpy** - Numerical Python used for Data Processing
- is written in C and C++ so operations are significantly faster than using Python
- Pandas, TensorFlow and PyTorch internally use Numpy
- Extrememly useful for Vectorized Operations without using any kind of loop

In [3]:
# python list
nums = [1,2,3,4,5]
print( 'Python List : ', nums, ' \t Type : ', type(nums) )

# numpy array
npArr_1 = np.array( nums ) 
print( 'Numpy Array : ', npArr_1, ' \t Type : ', type(npArr_1) )

Python List :  [1, 2, 3, 4, 5]  	 Type :  <class 'list'>
Numpy Array :  [1 2 3 4 5]  	 Type :  <class 'numpy.ndarray'>


### Vectorization 
- Simple
- For a Million Elements

In [4]:
# Simple
print( 'List requires loop : ', [ n + 10 for n in nums ] )
print( 'NumpyArray vectorized loop #1: ', npArr_1 + 10 )
print( 'NumpyArray vectorized loop #2: ', npArr_1 * 10 )

List requires loop :  [11, 12, 13, 14, 15]
NumpyArray vectorized loop #1:  [11 12 13 14 15]
NumpyArray vectorized loop #2:  [10 20 30 40 50]


In [5]:
# For a Million Elements
arrSize = 1000000

pyList = list( range(arrSize) )
npArr_2 = np.arange( arrSize )

print( "Performance Comparison for a total of ", arrSize, " elements : " )

print( " Addition using List Comprehension: " )
start = time.time()
res_py = [ n + 10 for n in pyList ]
time_py = time.time() - start 
print( "\t Python List Addition : ", time_py, " seconds " )
# print( "\t Python List Addition : ", round(time_py,5), " seconds " )

print( " Addition using Numpy Vectorization: " )
start = time.time()
res_np = npArr_2 + 10
time_np = time.time() - start 
print( "\t Numpy Array Addition : ", time_np, " seconds " )

print( "\n Addition Time Comparision : Numpy is ", round((time_py/time_np),3), " x faster" ) 

# Reset Values
pyList = list( range(arrSize) )
npArr_2 = np.arange( arrSize )

print( "\n Multiplication using List Comprehension: " )
start = time.time()
res_py = [ n * 10 for n in pyList ]
time_py = time.time() - start 
print( "\t Python List Multiplication : ", time_py, " seconds " )
# print( "\t Python List Addition : ", round(time_py,5), " seconds " )

print( " Multiplication using Numpy Vectorization: " )
start = time.time()
res_np = npArr_2 * 10
time_np = time.time() - start 
print( "\t Numpy Array Multiplication : ", time_np, " seconds " )

print( "\n Multiplication Time Comparision : Numpy is ", round((time_py/time_np),3), " x faster" ) 


Performance Comparison for a total of  1000000  elements : 
 Addition using List Comprehension: 
	 Python List Addition :  0.08899998664855957  seconds 
 Addition using Numpy Vectorization: 
	 Numpy Array Addition :  0.0040171146392822266  seconds 

 Addition Time Comparision : Numpy is  22.155  x faster

 Multiplication using List Comprehension: 
	 Python List Multiplication :  0.09903621673583984  seconds 
 Multiplication using Numpy Vectorization: 
	 Numpy Array Multiplication :  0.0039997100830078125  seconds 

 Multiplication Time Comparision : Numpy is  24.761  x faster


***

### Array Creation Numpy and Python

In [6]:
# Python List can have multiple data types
pyList = [ 1,2,3, 4.5, True, 'Hello' ]
print( 'Val : ', pyList, ' Type : ', type(pyList) )

# numpy array can only have one data type
np_Arr_int = np.array( [1,2,3,4,5] )
print( 'Val : ', np_Arr_int, ' Type : ', type(np_Arr_int), ' DataType: ', np_Arr_int.dtype )

np_Arr_float = np.array( [1.5,2.5,3.1,4.7,5] )
print( 'Val : ', np_Arr_float, ' Type : ', type(np_Arr_float), ' DataType: ', np_Arr_float.dtype )

np_Arr_str = np.array( ['ON','BC','QC','MB'] )
print( 'Val : ', np_Arr_str, ' Type : ', type(np_Arr_str) , ' DataType: ', np_Arr_str.dtype )

np_Arr_mixed = np.array( [ 1,2,3.5 ] ) # 1,2 - Integers but 3.5 is float so promoted to float
print( 'Val : ', np_Arr_mixed, ' Type : ', type(np_Arr_mixed), ' DataType: ', np_Arr_mixed.dtype )

Val :  [1, 2, 3, 4.5, True, 'Hello']  Type :  <class 'list'>
Val :  [1 2 3 4 5]  Type :  <class 'numpy.ndarray'>  DataType:  int64
Val :  [1.5 2.5 3.1 4.7 5. ]  Type :  <class 'numpy.ndarray'>  DataType:  float64
Val :  ['ON' 'BC' 'QC' 'MB']  Type :  <class 'numpy.ndarray'>  DataType:  <U2
Val :  [1.  2.  3.5]  Type :  <class 'numpy.ndarray'>  DataType:  float64


In [7]:
# Specify DataType while creating 
np_Arr_float = np.array( [1.5,2.5,3.5], dtype=np.float32 )
print( 'Val : ', np_Arr_float, 'Float32 DataType instead of Default Float64 : ', np_Arr_float.dtype )

np_Arr_mixed = np.array( [ 1,2,3.5 ] ) 
# 1,2 - Integers but 3.5 is float so promoted to float64 by defauly but change to float32
np_Arr_mixed = np_Arr_mixed.astype( np.float32 )
print( 'Val : ', np_Arr_mixed, ' Type : ', type(np_Arr_mixed), ' DataType: ', np_Arr_mixed.dtype )

Val :  [1.5 2.5 3.5] Float32 DataType instead of Default Float64 :  float32
Val :  [1.  2.  3.5]  Type :  <class 'numpy.ndarray'>  DataType:  float32


In [8]:
# Using np.arange() similar to range function - start, stop, step
np_Arr_int = np.arange( 0, 10, 1 )
print( 'arange() : ', np_Arr_int, ' Type : ', type(np_Arr_int) )

# np.linspace() - Evenly spaced numbers
np_Arr_float = np.linspace( 0, 1, 5 )
print( 'linspace() : ', np_Arr_float, ' Type : ', type(np_Arr_float) )

arange() :  [0 1 2 3 4 5 6 7 8 9]  Type :  <class 'numpy.ndarray'>
linspace() :  [0.   0.25 0.5  0.75 1.  ]  Type :  <class 'numpy.ndarray'>


In [9]:
# Arrays of Zeros
npArr_2 = np.zeros( 10 )
print( 'zeros(10) : ', npArr_2, ' Type : ', type(npArr_2) )
# Arrays of Ones
npArr_2 = np.ones( 5 )
print( 'ones(5) : ', npArr_2, ' Type : ', type(npArr_2) )

zeros(10) :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]  Type :  <class 'numpy.ndarray'>
ones(5) :  [1. 1. 1. 1. 1.]  Type :  <class 'numpy.ndarray'>


In [10]:
# Create Arrays with a specified Value (Shape and Valuetofill)
np_Arr_int = np.full (5, 11 ) # 
print( 'Create 5 element 1D Array filled with 11 as values : ', np_Arr_int )

Create 5 element 1D Array filled with 11 as values :  [11 11 11 11 11]


In [11]:
np_Arr_float = np.random.rand( 5 ) 
print( '5 random floating point values between 0 and 1: ', np_Arr_float )

np_Arr_int = np.random.randint( 10,20, size=5 )
print( '5 random integer values between 10 and 20: ', np_Arr_int )

5 random floating point values between 0 and 1:  [0.44694117 0.47962339 0.22528826 0.38414952 0.65559306]
5 random integer values between 10 and 20:  [10 15 11 14 14]


In [12]:
# Identity Matrix  

id_1 = np.eye(3)
print( '3x3 Identity Matrix : \n', id_1 )

id_2 = np.eye(2)
print( '2x2 Identity Matrix : \n', id_2 )

3x3 Identity Matrix : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
2x2 Identity Matrix : 
 [[1. 0.]
 [0. 1.]]


***

### Numpy Data-Types:
- **Homogeneous** - All Elements have the same type thus helping with memory usage and operations

In [13]:
np_Arr_int_2 = np.array( [ 1,2,3,4,5 ] )
print( 'INT Array : ', np_Arr_int_2, ' Type : ', np_Arr_int_2.dtype )
np_Arr_float_2 = np.array( [ 1.1,2.2,3.3 ] )
print( 'Float Array : ', np_Arr_float_2, ' Type : ', np_Arr_float_2.dtype )
np_Arr_mixed = np.array( [ 1,2.7,3 ] ) # Takes highest Data-Type so all converted to float
print( 'Mixed Int converted to float : ', np_Arr_mixed, ' Type : ', np_Arr_mixed.dtype )

np_Arr_int32 = np.array( [ 1,2,3,4,5 ], dtype=np.int32 )
print( 'Int32 Array instead of default Int64 : ', np_Arr_int32, ' Type : ', np_Arr_int32.dtype )

ap_Arr_float16 = np_Arr_mixed.astype(np.float16) 
print( 'Default Float64 converted to Float16 : ', ap_Arr_float16, ' Type : ', ap_Arr_float16.dtype )

print( "\n Memory consumed per element: \n \t np.int16/np.float16 - 2 Bytes, \n \t np.int32/np.float32 - 4 Bytes, \n \t np.int64/np.float64 - 8 Bytes" )

INT Array :  [1 2 3 4 5]  Type :  int64
Float Array :  [1.1 2.2 3.3]  Type :  float64
Mixed Int converted to float :  [1.  2.7 3. ]  Type :  float64
Int32 Array instead of default Int64 :  [1 2 3 4 5]  Type :  int32
Default Float64 converted to Float16 :  [1.  2.7 3. ]  Type :  float16

 Memory consumed per element: 
 	 np.int16/np.float16 - 2 Bytes, 
 	 np.int32/np.float32 - 4 Bytes, 
 	 np.int64/np.float64 - 8 Bytes


***

### Multi-Dimensional Arrays
- **Dimensions** - Number of Nested Arrays inside of a Numpy Array
- **Shape** - Values will be based on the number of dimensions, 1 value for 1D, 2 values for 2D and 3 values for 3D and so on

In [14]:
np_1D_Arr = np.array( [ 1,2,3,4,5 ] )
print( '1-Dimensional Array :', np_1D_Arr )
print( 'Shape : ', np_1D_Arr.shape, '\t Dimensions : ', np_1D_Arr.ndim, '\t Size: ', np_1D_Arr.size )

np_2D_Arr = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
print( '2-Dimensional Array :\n ', np_2D_Arr )
print( 'Shape : ', np_2D_Arr.shape, '\t Dimensions : ', np_2D_Arr.ndim, '\t Size: ', np_2D_Arr.size )


np_3D_Arr = np.array ([
    [  # First 2D layer
        [1, 2, 3],
        [4, 5, 6]
    ],
    [  # Second 2D layer
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print( '3-Dimensional Array :\n ', np_3D_Arr )
print( 'Shape : ', np_3D_Arr.shape, '\t Dimensions : ', np_3D_Arr.ndim, '\t Size: ', np_3D_Arr.size )
# Shape :  (2, 2, 3)  cause 2Layers, Two rows within each layer and 3 columns in each item

1-Dimensional Array : [1 2 3 4 5]
Shape :  (5,) 	 Dimensions :  1 	 Size:  5
2-Dimensional Array :
  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape :  (3, 3) 	 Dimensions :  2 	 Size:  9
3-Dimensional Array :
  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape :  (2, 2, 3) 	 Dimensions :  3 	 Size:  12


#### Create Multi-Dimensional Array with specific shapes

In [15]:
# 3 Rows and 4 columns
zeros_2D = np.zeros( (3,4) ) 
print( '2-Dimensional Zeros Array :\n ', zeros_2D )
print( 'Shape : ', zeros_2D.shape, '\t Dimensions : ', zeros_2D.ndim, '\t Size: ', zeros_2D.size )

# 2 x 3 x 4
ones_3D = np.ones( (2,3,4) )
print( '3-Dimensional Ones Array :\n ', ones_3D )
print( 'Shape : ', ones_3D.shape, '\t Dimensions : ', ones_3D.ndim, '\t Size: ', ones_3D.size )


2-Dimensional Zeros Array :
  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape :  (3, 4) 	 Dimensions :  2 	 Size:  12
3-Dimensional Ones Array :
  [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
Shape :  (2, 3, 4) 	 Dimensions :  3 	 Size:  24


In [16]:
TwoD_Arr = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12] ])
print( '2-Dimensional Array :\n ', TwoD_Arr )
print( 'Shape : ', TwoD_Arr.shape, '\t Dimensions : ', TwoD_Arr.ndim, '\t Size: ', TwoD_Arr.size )
print( 'DataType : ', TwoD_Arr.dtype, '\t Size of each element : ', TwoD_Arr.itemsize, 'Bytes \t Total Memory Used: ', TwoD_Arr.nbytes, 'Bytes' )
TwoD_Arr_Transpose = TwoD_Arr.T
print( 'Transpose of above Array :\n ', TwoD_Arr_Transpose )
print( 'Shape : ', TwoD_Arr_Transpose.shape, '\t Dimensions : ', TwoD_Arr_Transpose.ndim, '\t Size: ', TwoD_Arr_Transpose.size )

2-Dimensional Array :
  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape :  (3, 4) 	 Dimensions :  2 	 Size:  12
DataType :  int64 	 Size of each element :  8 Bytes 	 Total Memory Used:  96 Bytes
Transpose of above Array :
  [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Shape :  (4, 3) 	 Dimensions :  2 	 Size:  12


***

### Indexing and Slicing
- **Slicing** = [start, stop, step]
- **Indexing** = Particular Element

#### 1-D Array Indexing

In [17]:
np_1D_Arr = np.array( [ 10,20,30,40,50 ] )
print( 'Original Array : ', np_1D_Arr, '\t Shape : ', np_1D_Arr.shape )
print( 'First Element : ', np_1D_Arr[0] )
print( 'Last Element : ', np_1D_Arr[-1] )
print( 'First 3 Elements : ', np_1D_Arr[:3] )
print( 'Elements 1 to 3: ', np_1D_Arr[1:4] )
print( 'Even Position Elements: ', np_1D_Arr[::2] )
print( 'Odd Position Elements: ', np_1D_Arr[1::2] )

Original Array :  [10 20 30 40 50] 	 Shape :  (5,)
First Element :  10
Last Element :  50
First 3 Elements :  [10 20 30]
Elements 1 to 3:  [20 30 40]
Even Position Elements:  [10 30 50]
Odd Position Elements:  [20 40]


#### 2-D Array Indexing

In [18]:
# 2-D Array Indexing
np_2D_Arr = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
print( 'Original Array : \n ', np_2D_Arr, '\t Shape : ', np_2D_Arr.shape )
print( 'Element at Row 2, Column 3 = ', np_2D_Arr[1,2] ) # Row,Col
print( 'Element at Row 3, Column 2 = ', np_2D_Arr[2,2] ) # Row,Col
print( 'All Columns in First Row : ', np_2D_Arr[0,:] )
print( 'All Rows in Second Column : ', np_2D_Arr[:,1] )
print( 'Sub-Matrix : First 2 Rows, First 2 Columns: \n ', np_2D_Arr[0:2,0:2] )
print( 'Sub-Matrix : Last 2 Rows, Last 2 Columns: \n ', np_2D_Arr[1:3,1:3] )

Original Array : 
  [[1 2 3]
 [4 5 6]
 [7 8 9]] 	 Shape :  (3, 3)
Element at Row 2, Column 3 =  6
Element at Row 3, Column 2 =  9
All Columns in First Row :  [1 2 3]
All Rows in Second Column :  [2 5 8]
Sub-Matrix : First 2 Rows, First 2 Columns: 
  [[1 2]
 [4 5]]
Sub-Matrix : Last 2 Rows, Last 2 Columns: 
  [[5 6]
 [8 9]]


#### NP Array Boolean Indexing

In [19]:
np_Arr = np.array( [ 10,22,30,42,55,60,77,84,99 ] )
print( 'Original Array : ', np_Arr, '\t Shape : ', np_Arr.shape )
print( 'Elements Greater than 50 : ',  np_Arr[ np_Arr > 50 ] )
print( 'Even Numbers : ', np_Arr[ np_Arr % 2 == 0 ] )
print( 'Odd Numbers : ', np_Arr[ np_Arr % 2 == 1 ] )
print( 'Multiples of 7 : ', np_Arr[ np_Arr % 7 == 0 ] )

Original Array :  [10 22 30 42 55 60 77 84 99] 	 Shape :  (9,)
Elements Greater than 50 :  [55 60 77 84 99]
Even Numbers :  [10 22 30 42 60 84]
Odd Numbers :  [55 77 99]
Multiples of 7 :  [42 77 84]


### NumPy for Vectorized Operations without using any kind of loop

In [20]:
arr_1 = np.array( [1,2,3,4,5] )
print( 'Array #1 : ', arr_1 )

arr_2 = np.array( [6,7,8,9,10] )
print( 'Array #2 : ', arr_2 )

Array #1 :  [1 2 3 4 5]
Array #2 :  [ 6  7  8  9 10]


#### Element-wise Operations - Perform operations Element by Element 

In [21]:
print( 'Addition = ', arr_1 + arr_2 )
print( 'Subtraction = ', arr_1 - arr_2 )
print( 'Multiplication = ', arr_1 * arr_2 ) # Element-wise - Not Matrix Multiplication or Dot Product 
print( 'Division = ', arr_1 / arr_2 )
print( 'Square-Root Array #1 = ', np.sqrt(arr_1) )
print( 'Square-Root Array #2 = ', np.sqrt(arr_2) )

Addition =  [ 7  9 11 13 15]
Subtraction =  [-5 -5 -5 -5 -5]
Multiplication =  [ 6 14 24 36 50]
Division =  [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Square-Root Array #1 =  [1.         1.41421356 1.73205081 2.         2.23606798]
Square-Root Array #2 =  [2.44948974 2.64575131 2.82842712 3.         3.16227766]


#### Scalar Operations:
- **Broadcasting** - Same Value operations to every individual element inside the Numpy Array

In [22]:
print( 'Array #1 All Elements + 10 : ', arr_1 + 10 )
print( 'Array #2 All Elements * 5 : ', arr_2 * 5 )
print( 'Power/Exponential (Square) = ', arr_1 ** 2 )
print( 'Power/Exponential (Cube) = ', arr_1 ** 3 )

Array #1 All Elements + 10 :  [11 12 13 14 15]
Array #2 All Elements * 5 :  [30 35 40 45 50]
Power/Exponential (Square) =  [ 1  4  9 16 25]
Power/Exponential (Cube) =  [  1   8  27  64 125]


#### Comparison Operators

In [23]:
print( 'Array #2 > 7 = ', arr_2 > 7 )
print( 'Array #1 == 5 = ', arr_1 == 5 )
print( 'Array #2 <= 8 = ', arr_2 <= 8 )

Array #2 > 7 =  [False False  True  True  True]
Array #1 == 5 =  [False False False False  True]
Array #2 <= 8 =  [ True  True  True False False]


***

### Array Manipulation : Reshaping and Resizing
- Changing the Shape of Arrays is common in data processing

In [24]:
# np.arange( start, stop, step, dataType )
arr_3 = np.arange( 10, 33, 2, np.int16 )
print( 'arr_3 : ', arr_3, '\t Type : ', arr_3.dtype )

# arr_1D = np.arange( 13 ) 
# Will give an error - ValueError: cannot reshape array of size 13 into shape (3,4)

arr_1D = np.arange( 12 ) 
print( '\n 1-D Array : ', arr_1D, '\t Type : ', arr_1D.dtype )
print( 'Shape : ', arr_1D.shape, '\t Dimensions : ', arr_1D.ndim, '\t Size: ', arr_1D.size )
# Re-Shape changes view but does not copy the Data 
arr_reshaped = arr_1D.reshape( 3,4 )
# Ensure this shape matches the total number of elements in the original array - 12 = 3x4 matrix
print( '\n Reshaped Array : \n ', arr_reshaped )
print( 'Shape : ', arr_reshaped.shape, '\t Dimensions : ', arr_reshaped.ndim, '\t Size: ', arr_reshaped.size )

arr_2D = np.array([ [1,2,3], [4,5,6], [7,8,9], [10,11,12] ])
print( '\n 2-Dimensional Array :\n ', arr_2D )
print( 'Shape : ', arr_2D.shape, '\t Dimensions : ', arr_2D.ndim, '\t Size: ', arr_2D.size )

# Flatten 2D Array into 1D Array
arr_flattened = arr_2D.flatten()
print( '\n Flattenned Array : \n ', arr_flattened )
print( 'Shape : ', arr_flattened.shape, '\t Dimensions : ', arr_flattened.ndim, '\t Size: ', arr_flattened.size )

# Re-shape with Automatic Calculation (Auto-Calculate the dimensions with -1)
auto_reShaped_1D = arr_1D.reshape( 2, -1 )
print( '\n Auto reShaped 1D Array : \n ', auto_reShaped_1D )
print( 'Shape : ', auto_reShaped_1D.shape, '\t Dimensions : ', auto_reShaped_1D.ndim, '\t Size: ', auto_reShaped_1D.size )

auto_reShaped_2D = arr_2D.reshape( 6, -1 )
print( '\n Auto reShaped 2D Array : \n ', auto_reShaped_2D )
print( 'Shape : ', auto_reShaped_2D.shape, '\t Dimensions : ', auto_reShaped_2D.ndim, '\t Size: ', auto_reShaped_2D.size )

# Transpose means Columns become Rows or flipping the rows and columns
arr_transposed_2D = arr_2D.T
print( '\n Transposed 2D Array : \n ', arr_transposed_2D )
print( 'Shape : ', arr_transposed_2D.shape, '\t Dimensions : ', arr_transposed_2D.ndim, '\t Size: ', arr_transposed_2D.size )

arr_3 :  [10 12 14 16 18 20 22 24 26 28 30 32] 	 Type :  int16

 1-D Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11] 	 Type :  int64
Shape :  (12,) 	 Dimensions :  1 	 Size:  12

 Reshaped Array : 
  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape :  (3, 4) 	 Dimensions :  2 	 Size:  12

 2-Dimensional Array :
  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape :  (4, 3) 	 Dimensions :  2 	 Size:  12

 Flattenned Array : 
  [ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape :  (12,) 	 Dimensions :  1 	 Size:  12

 Auto reShaped 1D Array : 
  [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Shape :  (2, 6) 	 Dimensions :  2 	 Size:  12

 Auto reShaped 2D Array : 
  [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
Shape :  (6, 2) 	 Dimensions :  2 	 Size:  12

 Transposed 2D Array : 
  [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Shape :  (3, 4) 	 Dimensions :  2 	 Size:  12


#### Concatenation - Adding multiple matrices

In [25]:
arr_1 = np.array([1, 2, 3])
print('\nArray #1:\n', arr_1)
print('Shape :', arr_1.shape, '\tDimensions :', arr_1.ndim, '\tSize :', arr_1.size)

arr_2 = np.array([4, 5, 6])
print('\nArray #2:\n', arr_2)
print('Shape :', arr_2.shape, '\tDimensions :', arr_2.ndim, '\tSize :', arr_2.size)

# Vertical stacking: creates a 2D array with arrays as rows
print('\nVertical Concatenation (vStack):\n', np.vstack((arr_1, arr_2)))

# Horizontal stacking: joins the arrays into one longer 1D array
print('\nHorizontal Concatenation (hStack):\n', np.hstack((arr_1, arr_2)))

print('\nUsing Concatenate and Axes:')

# axis=0 is the only valid axis for concatenating 1D arrays
print('\nAxis-0:\n', np.concatenate((arr_1, arr_2), axis=0))

# Column stacking: places the arrays as columns in a 2D array
print('\nColumn Stacking:\n', np.column_stack((arr_1, arr_2)))


Array #1:
 [1 2 3]
Shape : (3,) 	Dimensions : 1 	Size : 3

Array #2:
 [4 5 6]
Shape : (3,) 	Dimensions : 1 	Size : 3

Vertical Concatenation (vStack):
 [[1 2 3]
 [4 5 6]]

Horizontal Concatenation (hStack):
 [1 2 3 4 5 6]

Using Concatenate and Axes:

Axis-0:
 [1 2 3 4 5 6]

Column Stacking:
 [[1 4]
 [2 5]
 [3 6]]


In [26]:
arr_1 = np.array([ [1,2,3], [4,5,6] ])
print( '\n Array #1 :\n ', arr_1 )
print( 'Shape : ', arr_1.shape, '\t Dimensions : ', arr_1.ndim, '\t Size: ', arr_1.size )

arr_2 = np.array([ [7,8,9], [10,11,12] ])
print( '\n Array #2 :\n ', arr_2 )
print( 'Shape : ', arr_2.shape, '\t Dimensions : ', arr_2.ndim, '\t Size: ', arr_2.size )

print( '\n Vertical Concatenation: (vStack):\n', np.vstack((arr_1,arr_2)) )
print( '\n Horizontal Concatenation: (hStack):\n', np.hstack((arr_1,arr_2)) )

print( '\n Using Concatenate and Axes:' )
print( '\n Axis-0 (Vertical) :\n', np.concatenate( (arr_1,arr_2), axis=0) )
print( '\n Axis-1 (Horizontal) :\n', np.concatenate( (arr_1,arr_2), axis=1) )

print( '\n Column Stacking:\n', np.column_stack((arr_1,arr_2)) )


 Array #1 :
  [[1 2 3]
 [4 5 6]]
Shape :  (2, 3) 	 Dimensions :  2 	 Size:  6

 Array #2 :
  [[ 7  8  9]
 [10 11 12]]
Shape :  (2, 3) 	 Dimensions :  2 	 Size:  6

 Vertical Concatenation: (vStack):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

 Horizontal Concatenation: (hStack):
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

 Using Concatenate and Axes:

 Axis-0 (Vertical) :
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

 Axis-1 (Horizontal) :
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

 Column Stacking:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


#### For 2D arrays, np.column_stack() and horizontal stacking (np.hstack() or np.concatenate(..., axis=1)) often give the same result because both place the second array's columns to the right of the first array.

***

### Numpy Concepts:
- **Dimensions(ndim)** - Number of Axes[num of nested arrays] (1 for 1D, 2 for 2D, 3 for 3D and so on)
- **Axis** - The dimension along which an operation is performed (starts from 0)
- **Shape** - Size of each dimension (eg, (4,3) means 4 rows and 3 columns)
- **For 2D Arrays**: `axis=0` = **rows**(vertical), `axis=1`=**columns**(horizontal)

#### Axes in Operations - Specifies the dimension to collapse

In [27]:
matrix_2D = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
print( '\n Matrix :\n ', matrix_2D )
print( 'Shape : ', matrix_2D.shape, '\t Dimensions : ', matrix_2D.ndim, '\t Size: ', matrix_2D.size )

# axis = 0 : Collapse Rows (Operate down the columns) -> One value per column
axis0_sum = np.sum( matrix_2D, axis=0 )
print( '\n Column Sum :\n ', axis0_sum )
print( 'Shape : ', axis0_sum.shape, '\t Dimensions : ', axis0_sum.ndim, '\t Size: ', axis0_sum.size )
for i in range(3):
        print( '\n Column ', i, ' Sum = ', matrix_2D[0,i], ' + ', matrix_2D[1,i], ' + ', matrix_2D[2,i], ' = ', axis0_sum[i] )

# axis = 1 : Collapse columns (Operate accross the Rows) -> One value per row
axis1_sum = np.sum( matrix_2D, axis=1 )
print( '\n Row Sum :\n ', axis1_sum )
print( 'Shape : ', axis1_sum.shape, '\t Dimensions : ', axis1_sum.ndim, '\t Size: ', axis1_sum.size )
for i in range(3):
        print( '\n Row ', i, ' Sum = ', matrix_2D[i,0], ' + ', matrix_2D[i,1], ' + ', matrix_2D[i,2], ' = ', axis1_sum[i] )


 Matrix :
  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape :  (3, 3) 	 Dimensions :  2 	 Size:  9

 Column Sum :
  [12 15 18]
Shape :  (3,) 	 Dimensions :  1 	 Size:  3

 Column  0  Sum =  1  +  4  +  7  =  12

 Column  1  Sum =  2  +  5  +  8  =  15

 Column  2  Sum =  3  +  6  +  9  =  18

 Row Sum :
  [ 6 15 24]
Shape :  (3,) 	 Dimensions :  1 	 Size:  3

 Row  0  Sum =  1  +  2  +  3  =  6

 Row  1  Sum =  4  +  5  +  6  =  15

 Row  2  Sum =  7  +  8  +  9  =  24


In [28]:
# 3D Array - (depth, rows, columns) or (samples,height,width)
pages_3D = np.array([
    [ [1,2,3],
    [4,5,6] ], #First 2D Slice (Page #0)
    [ [7,8,9],
    [10,11,12] ], #First 2D Slice (Page #1)
])

# Two pages, each with a 2x3 Matrix
print( '\n 3-D Array :\n ', matrix_2D )
print( 'Shape : ', pages_3D.shape, '\t Dimensions : ', pages_3D.ndim, '\t Size: ', pages_3D.size )
# Shape :  (2, 2, 3) - (depth=2, rows=2, columns=3)


 3-D Array :
  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape :  (2, 2, 3) 	 Dimensions :  3 	 Size:  12


In [29]:
# 3D Array - (depth, rows, columns) or (samples,height,width)
pages_3D = np.array([
    [ [1, 2, 3],
      [4, 5, 6] ],      #First 2D Slice (Page #0)

    [ [7, 8, 9],
      [10, 11, 12] ]    #First 2D Slice (Page #1)
])

print('\n3-D Array:\n', pages_3D)
print('Shape :', pages_3D.shape,
      '\tDimensions :', pages_3D.ndim,
      '\tSize :', pages_3D.size)

# axis = 0 : Collapse pages (operate through depth)
# Result: one 2D matrix with sums of corresponding positions
axis0_sum = np.sum(pages_3D, axis=0)

print('\naxis=0 Sum (Across Pages):\n', axis0_sum)
print('Shape :', axis0_sum.shape,
      '\tDimensions :', axis0_sum.ndim,
      '\tSize :', axis0_sum.size)

for r in range(pages_3D.shape[1]):
    for c in range(pages_3D.shape[2]):
        print('Position [', r, ',', c, '] :',
              pages_3D[0, r, c], '+', pages_3D[1, r, c],
              '=', axis0_sum[r, c])

# axis = 1 : Collapse rows within each page
# Result: one row per page
axis1_sum = np.sum(pages_3D, axis=1)

print('\naxis=1 Sum (Down Rows):\n', axis1_sum)
print('Shape :', axis1_sum.shape,
      '\tDimensions :', axis1_sum.ndim,
      '\tSize :', axis1_sum.size)

for p in range(pages_3D.shape[0]):
    for c in range(pages_3D.shape[2]):
        print('Page', p, 'Column', c, ':',
              pages_3D[p, 0, c], '+', pages_3D[p, 1, c],
              '=', axis1_sum[p, c])

# axis = 2 : Collapse columns within each row
# Result: one value per row in each page
axis2_sum = np.sum(pages_3D, axis=2)

print('\naxis=2 Sum (Across Columns):\n', axis2_sum)
print('Shape :', axis2_sum.shape,
      '\tDimensions :', axis2_sum.ndim,
      '\tSize :', axis2_sum.size)

for p in range(pages_3D.shape[0]):
    for r in range(pages_3D.shape[1]):
        print('Page', p, 'Row', r, ':',
              pages_3D[p, r, 0], '+',
              pages_3D[p, r, 1], '+',
              pages_3D[p, r, 2],
              '=', axis2_sum[p, r])


3-D Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape : (2, 2, 3) 	Dimensions : 3 	Size : 12

axis=0 Sum (Across Pages):
 [[ 8 10 12]
 [14 16 18]]
Shape : (2, 3) 	Dimensions : 2 	Size : 6
Position [ 0 , 0 ] : 1 + 7 = 8
Position [ 0 , 1 ] : 2 + 8 = 10
Position [ 0 , 2 ] : 3 + 9 = 12
Position [ 1 , 0 ] : 4 + 10 = 14
Position [ 1 , 1 ] : 5 + 11 = 16
Position [ 1 , 2 ] : 6 + 12 = 18

axis=1 Sum (Down Rows):
 [[ 5  7  9]
 [17 19 21]]
Shape : (2, 3) 	Dimensions : 2 	Size : 6
Page 0 Column 0 : 1 + 4 = 5
Page 0 Column 1 : 2 + 5 = 7
Page 0 Column 2 : 3 + 6 = 9
Page 1 Column 0 : 7 + 10 = 17
Page 1 Column 1 : 8 + 11 = 19
Page 1 Column 2 : 9 + 12 = 21

axis=2 Sum (Across Columns):
 [[ 6 15]
 [24 33]]
Shape : (2, 2) 	Dimensions : 2 	Size : 4
Page 0 Row 0 : 1 + 2 + 3 = 6
Page 0 Row 1 : 4 + 5 + 6 = 15
Page 1 Row 0 : 7 + 8 + 9 = 24
Page 1 Row 1 : 10 + 11 + 12 = 33


***

### Statistical Operations in Numpy

In [30]:
vector = np.array([20, 49, 49, 23, 53, 53, 20, 18, 20, 38, 23, 18] )
print( '\n Vector : ', vector )

print( '\n Basic Statistics:' )
print( f" \t Sum = {np.sum(vector)} " ) # Total
print( f" \t Mean = {np.mean(vector)} " ) #Average

# Median: the middle value in a dataset when the numbers are arranged in 
#  ascending or descending order. If there are two middle values 
# (even count), the median is their average.  
print( f" \t Median = {np.median(vector)} " ) 

# Standard deviation: measures how spread out values are from the mean; 
# a higher value means more variability, while a lower value 
# means data is closer to the average.  
print( f" \t Standard Deviation = { round(np.std(vector),4) } " )

# Variance: measures the average squared deviation of values from the mean;
# a higher value indicates greater spread in the data, while a lower value
# means values are more tightly clustered around the average.
print( f" \t Variance = {np.var(vector)} " )

# Minimum and max from Vector
print( f" \t Min = {np.min(vector)} " )
print( f" \t Max = {np.max(vector)} " )
print( f" \t Index of Min = {np.argmin(vector)} " )
print( f" \t Index of Max = {np.argmax(vector)} " )

# Range of data (max - min)
print( f" \t Range (Max-Min) : {np.max(vector)} - {np.min(vector)} = {np.max(vector) - np.min(vector)}" )


 Vector :  [20 49 49 23 53 53 20 18 20 38 23 18]

 Basic Statistics:
 	 Sum = 384 
 	 Mean = 32.0 
 	 Median = 23.0 
 	 Standard Deviation = 14.3817 
 	 Variance = 206.83333333333334 
 	 Min = 18 
 	 Max = 53 
 	 Index of Min = 7 
 	 Index of Max = 4 
 	 Range (Max-Min) : 53 - 18 = 35


In [31]:
matrix_2D = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
print( '\n Matrix :\n ', matrix_2D )
print( 'Shape : ', matrix_2D.shape, '\t Dimensions : ', matrix_2D.ndim, '\t Size: ', matrix_2D.size )

print('\n2-D Array Statistics:')

# Overall statistics (all elements in the matrix)
print(f"\t Sum = {np.sum(matrix_2D)}")
print(f"\t Mean = {np.mean(matrix_2D)}")
print(f"\t Median = {np.median(matrix_2D)}")
print(f"\t Standard Deviation = {np.std(matrix_2D)}")
print(f"\t Variance = {np.var(matrix_2D)}")
print(f"\t Min = {np.min(matrix_2D)}")
print(f"\t Max = {np.max(matrix_2D)}")
print(f"\t Index of Min = {np.unravel_index(np.argmin(matrix_2D), matrix_2D.shape)}")
print(f"\t Index of Max = {np.unravel_index(np.argmax(matrix_2D), matrix_2D.shape)}")

# Row-wise statistics
print('\nRow-wise Statistics:')
print(f"\t Row Sum = {np.sum(matrix_2D, axis=1)}")
print(f"\t Row Mean = {np.mean(matrix_2D, axis=1)}")
print(f"\t Row Min = {np.min(matrix_2D, axis=1)}")
print(f"\t Row Max = {np.max(matrix_2D, axis=1)}")

# Column-wise statistics
print('\nColumn-wise Statistics:')
print(f"\t Column Sum = {np.sum(matrix_2D, axis=0)}")
print(f"\t Column Mean = {np.mean(matrix_2D, axis=0)}")
print(f"\t Column Min = {np.min(matrix_2D, axis=0)}")
print(f"\t Column Max = {np.max(matrix_2D, axis=0)}")



 Matrix :
  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape :  (3, 3) 	 Dimensions :  2 	 Size:  9

2-D Array Statistics:
	 Sum = 45
	 Mean = 5.0
	 Median = 5.0
	 Standard Deviation = 2.581988897471611
	 Variance = 6.666666666666667
	 Min = 1
	 Max = 9
	 Index of Min = (np.int64(0), np.int64(0))
	 Index of Max = (np.int64(2), np.int64(2))

Row-wise Statistics:
	 Row Sum = [ 6 15 24]
	 Row Mean = [2. 5. 8.]
	 Row Min = [1 4 7]
	 Row Max = [3 6 9]

Column-wise Statistics:
	 Column Sum = [12 15 18]
	 Column Mean = [4. 5. 6.]
	 Column Min = [1 2 3]
	 Column Max = [7 8 9]


***

### Linear Algebra

In [32]:
mat_1 = np.array([ [1,2], [3,4] ])
print( '\n Matrix #1 :\n ', mat_1 )
print( 'Shape : ', mat_1.shape, '\t Dimensions : ', mat_1.ndim, '\t Size: ', mat_1.size )

mat_2 = np.array([ [5,6], [7,8] ])
print( '\n Matrix #2 :\n ', mat_2 )
print( 'Shape : ', mat_2.shape, '\t Dimensions : ', mat_2.ndim, '\t Size: ', mat_2.size )

print( '\n Element-wise Multiplication: (mat_1 * mat_2) = \n', (mat_1 * mat_2) )
# NOT matrix multiplication, just position-by-position multiplication.
# [[1*5   2*6]
#  [3*7   4*8]]
# =
# [[5   12]
#  [21  32]]

print( 'Matrix Properties:' )
print( f" Determinant of Matrix 1 = {np.linalg.det(mat_1)} " )
print( f" Inverse of Matrix 2 = \n {np.linalg.inv(mat_2)} " )
print( f" Transpose of Matrix 1 = \n {mat_1.T} " )
eigenValues, eigenVectors = np.linalg.eig( mat_1 )
print( f" EigenValues of Matrix 1 =  {eigenValues} " )
print( f" EigenVectors of Matrix 1 = \n {eigenVectors} " )

# Dot Product (Matrix Multiplication) - row × column multiplication:

print( 'Matrix Properties:' )
print( f" Dot Product of Matrices \n {mat_1} \n and \n {mat_2} \n = \n { np.dot(mat_1,mat_2) }")

# First row of Matrix 1 × columns of Matrix 2:
# (1×5 + 2×7) = 5 + 14 = 19  
# (1×6 + 2×8) = 6 + 16 = 22

# Second row of Matrix 1 × columns of Matrix 2:
# (3×5 + 4×7) = 15 + 28 = 43  
# (3×6 + 4×8) = 18 + 32 = 50

# Result:
# [[19 22]
#  [43 50]]

vector_1 = np.array( [1,2,3] )
vector_2 = np.array( [4,5,6] )
print( '\n Vector #1 : ', vector_1, ' Vector #2 : ', vector_2 )
print( f" Dot Product of Vectors {vector_1} and {vector_2} = { np.dot(vector_1,vector_2) }")

# Calculation:
# (1×4) + (2×5) + (3×6)
# = 4 + 10 + 18
# = 32


 Matrix #1 :
  [[1 2]
 [3 4]]
Shape :  (2, 2) 	 Dimensions :  2 	 Size:  4

 Matrix #2 :
  [[5 6]
 [7 8]]
Shape :  (2, 2) 	 Dimensions :  2 	 Size:  4

 Element-wise Multiplication: (mat_1 * mat_2) = 
 [[ 5 12]
 [21 32]]
Matrix Properties:
 Determinant of Matrix 1 = -2.0000000000000004 
 Inverse of Matrix 2 = 
 [[-4.   3. ]
 [ 3.5 -2.5]] 
 Transpose of Matrix 1 = 
 [[1 3]
 [2 4]] 
 EigenValues of Matrix 1 =  [-0.37228132  5.37228132] 
 EigenVectors of Matrix 1 = 
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]] 
Matrix Properties:
 Dot Product of Matrices 
 [[1 2]
 [3 4]] 
 and 
 [[5 6]
 [7 8]] 
 = 
 [[19 22]
 [43 50]]

 Vector #1 :  [1 2 3]  Vector #2 :  [4 5 6]
 Dot Product of Vectors [1 2 3] and [4 5 6] = 32


***

### Numpy Array Methods:

In [33]:
nums = np.array([20, 49, 33, 23, 54, 53, 23, 18, 27, 38]) 

print( 'Numbers Initially : ', nums )

print( '\t Sorted using Numpy - returns a sorted copy ', np.sort( nums ) )
print( '\t Original Array unchanged ', nums )
print( '\t Numbers Reversed : ', nums[::-1] )
ascending_order = np.sort(nums)
print( '\t Numbers Sort Ascending : ', ascending_order )
descending_order = ascending_order[::-1]
print( '\t Numbers Sort Descending : ', descending_order )

matrix = np.array([
    [20, 49, 33],
    [23, 54, 53],
    [23, 18, 27]
])

print('\n 2D Array Initially:\n', matrix)

# Sort each row in ascending order
sorted_rows = np.sort(matrix, axis=1)
print('\n Rows Sorted Ascending:\n', sorted_rows)

# Original matrix remains unchanged
print('\n Original Matrix Unchanged:\n', matrix)

# Reverse the row order
print('\n Matrix Rows Reversed:\n', matrix[::-1])

# Reverse the columns in each row
print('\n Matrix Columns Reversed:\n', matrix[:, ::-1])

# Sort each row in descending order
descending_rows = np.sort(matrix, axis=1)[:, ::-1]
print('\n Rows Sorted Descending:\n', descending_rows)

# Sort each column in ascending order
sorted_columns = np.sort(matrix, axis=0)
print('\n Columns Sorted Ascending:\n', sorted_columns)

# Sort each column in descending order
descending_columns = np.sort(matrix, axis=0)[::-1]
print('\n Columns Sorted Descending:\n', descending_columns)

Numbers Initially :  [20 49 33 23 54 53 23 18 27 38]
	 Sorted using Numpy - returns a sorted copy  [18 20 23 23 27 33 38 49 53 54]
	 Original Array unchanged  [20 49 33 23 54 53 23 18 27 38]
	 Numbers Reversed :  [38 27 18 23 53 54 23 33 49 20]
	 Numbers Sort Ascending :  [18 20 23 23 27 33 38 49 53 54]
	 Numbers Sort Descending :  [54 53 49 38 33 27 23 23 20 18]

 2D Array Initially:
 [[20 49 33]
 [23 54 53]
 [23 18 27]]

 Rows Sorted Ascending:
 [[20 33 49]
 [23 53 54]
 [18 23 27]]

 Original Matrix Unchanged:
 [[20 49 33]
 [23 54 53]
 [23 18 27]]

 Matrix Rows Reversed:
 [[23 18 27]
 [23 54 53]
 [20 49 33]]

 Matrix Columns Reversed:
 [[33 49 20]
 [53 54 23]
 [27 18 23]]

 Rows Sorted Descending:
 [[49 33 20]
 [54 53 23]
 [27 23 18]]

 Columns Sorted Ascending:
 [[20 18 27]
 [23 49 33]
 [23 54 53]]

 Columns Sorted Descending:
 [[23 54 53]
 [23 49 33]
 [20 18 27]]


In [34]:
nums = np.array([20, 49, 49, 23, 53, 53, 20, 18, 20, 38, 23, 18] )

print( 'Numbers with duplicates : ', nums )
unique_nums = np.unique(nums)
print( 'Unique Values : ', unique_nums )

print( 'Search where value is greater than 20 (Positions): ', np.where( unique_nums > 20 ) )
print( 'Search where value is greater than 20 (Actual values): ', unique_nums[np.where( unique_nums > 20 )] )

matrix = np.array([
    [20, 49, 49],
    [23, 53, 53],
    [20, 18, 20],
    [38, 23, 18]
])

print('\n 2D Array with duplicates:\n', matrix)

# Unique values in the entire 2D array
unique_vals = np.unique(matrix)
print('\nUnique Values:', unique_vals)

# Find positions where values are greater than 20
positions = np.where(matrix > 20)
print('\nSearch where value is greater than 20 (Row indices):', positions[0])
print('Search where value is greater than 20 (Column indices):', positions[1])

# Show the (row, column) pairs
print('Search where value is greater than 20 (Positions):')
for r, c in zip(positions[0], positions[1]):
    print(f'\t({r}, {c})')

# Actual values greater than 20
print('\nSearch where value is greater than 20 (Actual values):',
      matrix[positions])

Numbers with duplicates :  [20 49 49 23 53 53 20 18 20 38 23 18]
Unique Values :  [18 20 23 38 49 53]
Search where value is greater than 20 (Positions):  (array([2, 3, 4, 5]),)
Search where value is greater than 20 (Actual values):  [23 38 49 53]

 2D Array with duplicates:
 [[20 49 49]
 [23 53 53]
 [20 18 20]
 [38 23 18]]

Unique Values: [18 20 23 38 49 53]

Search where value is greater than 20 (Row indices): [0 0 1 1 1 3 3]
Search where value is greater than 20 (Column indices): [1 2 0 1 2 0 1]
Search where value is greater than 20 (Positions):
	(0, 1)
	(0, 2)
	(1, 0)
	(1, 1)
	(1, 2)
	(3, 0)
	(3, 1)

Search where value is greater than 20 (Actual values): [49 49 23 53 53 38 23]


***

### Student Score Analysis

In [35]:
# Simulate student test scores (3 tests, 5 students)
scores = np.array([
    [72, 85, 79],   # Student 1
    [91, 88, 94],   # Student 2
    [67, 74, 70],   # Student 3
    [99, 95, 97],   # Student 4
    [83, 81, 86]    # Student 5
])

print("Test Scores Matrix (5 students, 3 tests):")
print(scores)

# Calculate statistics
print("\n--- Student Statistics ---")
student_averages = np.mean(scores, axis=1)
print("Average score per student:", student_averages)
print("Best student average:", np.max(student_averages))
print("Student with best average (index):", np.argmax(student_averages))

print("\n--- Test Statistics ---")
test_averages = np.mean(scores, axis=0)
print("Average score per test:", test_averages)
print("Hardest test (lowest average):", np.argmin(test_averages))
print("Easiest test (highest average):", np.argmax(test_averages))

# Find students who scored above 90 in all tests
excellent_students = np.all(scores > 90, axis=1)
print("\n--- Excellent Students (all tests > 90) ---")
print("Boolean mask:", excellent_students)
print("Indices:", np.where(excellent_students)[0])
print("Scores of excellent students: ", scores[excellent_students] )

Test Scores Matrix (5 students, 3 tests):
[[72 85 79]
 [91 88 94]
 [67 74 70]
 [99 95 97]
 [83 81 86]]

--- Student Statistics ---
Average score per student: [78.66666667 91.         70.33333333 97.         83.33333333]
Best student average: 97.0
Student with best average (index): 3

--- Test Statistics ---
Average score per test: [82.4 84.6 85.2]
Hardest test (lowest average): 0
Easiest test (highest average): 2

--- Excellent Students (all tests > 90) ---
Boolean mask: [False False False  True False]
Indices: [3]
Scores of excellent students:  [[99 95 97]]


In [36]:
# Simulate student test scores (3 tests, 5 students)
scores = np.array([
    [72, 85, 79],   # Student 1
    [91, 88, 94],   # Student 2
    [67, 74, 70],   # Student 3
    [99, 95, 97],   # Student 4
    [83, 81, 86]    # Student 5
])

print("Test Scores Matrix (5 students, 3 tests):")
print(scores)

# Calculate statistics
print("\n--- Student Statistics ---")
student_averages = np.mean(scores, axis=1)
print("Average score per student:", student_averages)

print("Best student average:", np.max(student_averages))
print("Student with best average (index):", np.argmax(student_averages))

print("Worst student average:", np.min(student_averages))
print("Student with worst average (index):", np.argmin(student_averages))

print("\nScores of best student:")
print(scores[np.argmax(student_averages)])

print("\nScores of worst student:")
print(scores[np.argmin(student_averages)])

print("\n--- Test Statistics ---")
test_averages = np.mean(scores, axis=0)
print("Average score per test:", test_averages)
print("Hardest test (lowest average):", np.argmin(test_averages))
print("Easiest test (highest average):", np.argmax(test_averages))

# Find students who scored above 90 in all tests
excellent_students = np.all(scores > 90, axis=1)
print("\n--- Excellent Students (all tests > 90) ---")
print("Boolean mask:", excellent_students)
print("Indices:", np.where(excellent_students)[0])
print("Scores of excellent students:")
print(scores[excellent_students])

Test Scores Matrix (5 students, 3 tests):
[[72 85 79]
 [91 88 94]
 [67 74 70]
 [99 95 97]
 [83 81 86]]

--- Student Statistics ---
Average score per student: [78.66666667 91.         70.33333333 97.         83.33333333]
Best student average: 97.0
Student with best average (index): 3
Worst student average: 70.33333333333333
Student with worst average (index): 2

Scores of best student:
[99 95 97]

Scores of worst student:
[67 74 70]

--- Test Statistics ---
Average score per test: [82.4 84.6 85.2]
Hardest test (lowest average): 0
Easiest test (highest average): 2

--- Excellent Students (all tests > 90) ---
Boolean mask: [False False False  True False]
Indices: [3]
Scores of excellent students:
[[99 95 97]]


In [37]:
# Simulate student test scores (3 tests, 10 students)
scores = np.array([
    [72, 85, 79],   # Student 1
    [91, 88, 94],   # Student 2
    [45, 38, 50],   # Student 3 (low scores)
    [99, 95, 97],   # Student 4
    [83, 81, 86],   # Student 5
    [60, 55, 58],   # Student 6
    [30, 42, 47],   # Student 7 (low scores)
    [88, 92, 85],   # Student 8
    [49, 51, 46],   # Student 9 (low scores)
    [77, 73, 80]    # Student 10
])

print("Test Scores Matrix (10 students, 3 tests):")
print(scores)

# Calculate statistics
print("\n--- Student Statistics ---")
student_averages = np.mean(scores, axis=1)
print("Average score per student:", student_averages)

print("Best student average:", np.max(student_averages))
print("Student with best average (index):", np.argmax(student_averages))

print("Worst student average:", np.min(student_averages))
print("Student with worst average (index):", np.argmin(student_averages))

print("\nScores of best student:")
print(scores[np.argmax(student_averages)])

print("\nScores of worst student:")
print(scores[np.argmin(student_averages)])

print("\n--- Test Statistics ---")
test_averages = np.mean(scores, axis=0)
print("Average score per test:", test_averages)
print("Hardest test (lowest average):", np.argmin(test_averages))
print("Easiest test (highest average):", np.argmax(test_averages))

# Excellent students (all scores > 90)
excellent_students = np.all(scores > 90, axis=1)
print("\n--- Excellent Students (all tests > 90) ---")
print("Boolean mask:", excellent_students)
print("Indices:", np.where(excellent_students)[0])
print("Scores of excellent students:")
print(scores[excellent_students])

# Worst students (any score < 50)
worst_students = np.any(scores < 50, axis=1)
print("\n--- Worst Students (any test < 50) ---")
print("Boolean mask:", worst_students)
print("Indices:", np.where(worst_students)[0])
print("Scores of worst students:")
print(scores[worst_students])

Test Scores Matrix (10 students, 3 tests):
[[72 85 79]
 [91 88 94]
 [45 38 50]
 [99 95 97]
 [83 81 86]
 [60 55 58]
 [30 42 47]
 [88 92 85]
 [49 51 46]
 [77 73 80]]

--- Student Statistics ---
Average score per student: [78.66666667 91.         44.33333333 97.         83.33333333 57.66666667
 39.66666667 88.33333333 48.66666667 76.66666667]
Best student average: 97.0
Student with best average (index): 3
Worst student average: 39.666666666666664
Student with worst average (index): 6

Scores of best student:
[99 95 97]

Scores of worst student:
[30 42 47]

--- Test Statistics ---
Average score per test: [69.4 70.  72.2]
Hardest test (lowest average): 0
Easiest test (highest average): 2

--- Excellent Students (all tests > 90) ---
Boolean mask: [False False False  True False False False False False False]
Indices: [3]
Scores of excellent students:
[[99 95 97]]

--- Worst Students (any test < 50) ---
Boolean mask: [False False  True False False False  True False  True False]
Indices: [2 6 8

***